/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilesystemDetectionConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesystemDetectionConfig{}

// FilesystemDetectionConfig Filesystem path detection settings
type FilesystemDetectionConfig struct {
	// Enable filesystem path detection (disabled by default as it can be noisy)
	Enabled *bool `json:"enabled,omitempty"`
	// Action when filesystem paths are detected
	Action *string `json:"action,omitempty"`
	// Path patterns to block (e.g., /etc/passwd, ~/.ssh)
	BlockedPaths []string `json:"blocked_paths,omitempty"`
}

// NewFilesystemDetectionConfig instantiates a new FilesystemDetectionConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesystemDetectionConfig() *FilesystemDetectionConfig {
	this := FilesystemDetectionConfig{}
	var enabled bool = false
	this.Enabled = &enabled
	var action string = "log"
	this.Action = &action
	return &this
}

// NewFilesystemDetectionConfigWithDefaults instantiates a new FilesystemDetectionConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesystemDetectionConfigWithDefaults() *FilesystemDetectionConfig {
	this := FilesystemDetectionConfig{}
	var enabled bool = false
	this.Enabled = &enabled
	var action string = "log"
	this.Action = &action
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *FilesystemDetectionConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemDetectionConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *FilesystemDetectionConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *FilesystemDetectionConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *FilesystemDetectionConfig) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemDetectionConfig) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *FilesystemDetectionConfig) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *FilesystemDetectionConfig) SetAction(v string) {
	o.Action = &v
}

// GetBlockedPaths returns the BlockedPaths field value if set, zero value otherwise.
func (o *FilesystemDetectionConfig) GetBlockedPaths() []string {
	if o == nil || IsNil(o.BlockedPaths) {
		var ret []string
		return ret
	}
	return o.BlockedPaths
}

// GetBlockedPathsOk returns a tuple with the BlockedPaths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemDetectionConfig) GetBlockedPathsOk() ([]string, bool) {
	if o == nil || IsNil(o.BlockedPaths) {
		return nil, false
	}
	return o.BlockedPaths, true
}

// HasBlockedPaths returns a boolean if a field has been set.
func (o *FilesystemDetectionConfig) HasBlockedPaths() bool {
	if o != nil && !IsNil(o.BlockedPaths) {
		return true
	}

	return false
}

// SetBlockedPaths gets a reference to the given []string and assigns it to the BlockedPaths field.
func (o *FilesystemDetectionConfig) SetBlockedPaths(v []string) {
	o.BlockedPaths = v
}

func (o FilesystemDetectionConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesystemDetectionConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.BlockedPaths) {
		toSerialize["blocked_paths"] = o.BlockedPaths
	}
	return toSerialize, nil
}

type NullableFilesystemDetectionConfig struct {
	value *FilesystemDetectionConfig
	isSet bool
}

func (v NullableFilesystemDetectionConfig) Get() *FilesystemDetectionConfig {
	return v.value
}

func (v *NullableFilesystemDetectionConfig) Set(val *FilesystemDetectionConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesystemDetectionConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesystemDetectionConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesystemDetectionConfig(val *FilesystemDetectionConfig) *NullableFilesystemDetectionConfig {
	return &NullableFilesystemDetectionConfig{value: val, isSet: true}
}

func (v NullableFilesystemDetectionConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesystemDetectionConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


