/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TreasurySignerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TreasurySignerResponse{}

// TreasurySignerResponse struct for TreasurySignerResponse
type TreasurySignerResponse struct {
	Id *string `json:"id,omitempty"`
	SignerType *string `json:"signer_type,omitempty"`
	SignerId *string `json:"signer_id,omitempty"`
	SignerAddress *string `json:"signer_address,omitempty"`
	AddedAt *time.Time `json:"added_at,omitempty"`
}

// NewTreasurySignerResponse instantiates a new TreasurySignerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTreasurySignerResponse() *TreasurySignerResponse {
	this := TreasurySignerResponse{}
	return &this
}

// NewTreasurySignerResponseWithDefaults instantiates a new TreasurySignerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTreasurySignerResponseWithDefaults() *TreasurySignerResponse {
	this := TreasurySignerResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TreasurySignerResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreasurySignerResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TreasurySignerResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TreasurySignerResponse) SetId(v string) {
	o.Id = &v
}

// GetSignerType returns the SignerType field value if set, zero value otherwise.
func (o *TreasurySignerResponse) GetSignerType() string {
	if o == nil || IsNil(o.SignerType) {
		var ret string
		return ret
	}
	return *o.SignerType
}

// GetSignerTypeOk returns a tuple with the SignerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreasurySignerResponse) GetSignerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SignerType) {
		return nil, false
	}
	return o.SignerType, true
}

// HasSignerType returns a boolean if a field has been set.
func (o *TreasurySignerResponse) HasSignerType() bool {
	if o != nil && !IsNil(o.SignerType) {
		return true
	}

	return false
}

// SetSignerType gets a reference to the given string and assigns it to the SignerType field.
func (o *TreasurySignerResponse) SetSignerType(v string) {
	o.SignerType = &v
}

// GetSignerId returns the SignerId field value if set, zero value otherwise.
func (o *TreasurySignerResponse) GetSignerId() string {
	if o == nil || IsNil(o.SignerId) {
		var ret string
		return ret
	}
	return *o.SignerId
}

// GetSignerIdOk returns a tuple with the SignerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreasurySignerResponse) GetSignerIdOk() (*string, bool) {
	if o == nil || IsNil(o.SignerId) {
		return nil, false
	}
	return o.SignerId, true
}

// HasSignerId returns a boolean if a field has been set.
func (o *TreasurySignerResponse) HasSignerId() bool {
	if o != nil && !IsNil(o.SignerId) {
		return true
	}

	return false
}

// SetSignerId gets a reference to the given string and assigns it to the SignerId field.
func (o *TreasurySignerResponse) SetSignerId(v string) {
	o.SignerId = &v
}

// GetSignerAddress returns the SignerAddress field value if set, zero value otherwise.
func (o *TreasurySignerResponse) GetSignerAddress() string {
	if o == nil || IsNil(o.SignerAddress) {
		var ret string
		return ret
	}
	return *o.SignerAddress
}

// GetSignerAddressOk returns a tuple with the SignerAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreasurySignerResponse) GetSignerAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SignerAddress) {
		return nil, false
	}
	return o.SignerAddress, true
}

// HasSignerAddress returns a boolean if a field has been set.
func (o *TreasurySignerResponse) HasSignerAddress() bool {
	if o != nil && !IsNil(o.SignerAddress) {
		return true
	}

	return false
}

// SetSignerAddress gets a reference to the given string and assigns it to the SignerAddress field.
func (o *TreasurySignerResponse) SetSignerAddress(v string) {
	o.SignerAddress = &v
}

// GetAddedAt returns the AddedAt field value if set, zero value otherwise.
func (o *TreasurySignerResponse) GetAddedAt() time.Time {
	if o == nil || IsNil(o.AddedAt) {
		var ret time.Time
		return ret
	}
	return *o.AddedAt
}

// GetAddedAtOk returns a tuple with the AddedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TreasurySignerResponse) GetAddedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AddedAt) {
		return nil, false
	}
	return o.AddedAt, true
}

// HasAddedAt returns a boolean if a field has been set.
func (o *TreasurySignerResponse) HasAddedAt() bool {
	if o != nil && !IsNil(o.AddedAt) {
		return true
	}

	return false
}

// SetAddedAt gets a reference to the given time.Time and assigns it to the AddedAt field.
func (o *TreasurySignerResponse) SetAddedAt(v time.Time) {
	o.AddedAt = &v
}

func (o TreasurySignerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TreasurySignerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SignerType) {
		toSerialize["signer_type"] = o.SignerType
	}
	if !IsNil(o.SignerId) {
		toSerialize["signer_id"] = o.SignerId
	}
	if !IsNil(o.SignerAddress) {
		toSerialize["signer_address"] = o.SignerAddress
	}
	if !IsNil(o.AddedAt) {
		toSerialize["added_at"] = o.AddedAt
	}
	return toSerialize, nil
}

type NullableTreasurySignerResponse struct {
	value *TreasurySignerResponse
	isSet bool
}

func (v NullableTreasurySignerResponse) Get() *TreasurySignerResponse {
	return v.value
}

func (v *NullableTreasurySignerResponse) Set(val *TreasurySignerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTreasurySignerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTreasurySignerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTreasurySignerResponse(val *TreasurySignerResponse) *NullableTreasurySignerResponse {
	return &NullableTreasurySignerResponse{value: val, isSet: true}
}

func (v NullableTreasurySignerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTreasurySignerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


