/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the SubscriptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionResponse{}

// SubscriptionResponse struct for SubscriptionResponse
type SubscriptionResponse struct {
	Tier *string `json:"tier,omitempty"`
	Interval *string `json:"interval,omitempty"`
	PeriodEnd *time.Time `json:"period_end,omitempty"`
	Status *string `json:"status,omitempty"`
	CreditBalanceCents *int32 `json:"credit_balance_cents,omitempty"`
	CreditBalanceUsd *string `json:"credit_balance_usd,omitempty"`
	OverageMethod *string `json:"overage_method,omitempty"`
	Usage *SubscriptionResponseUsage `json:"usage,omitempty"`
}

// NewSubscriptionResponse instantiates a new SubscriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionResponse() *SubscriptionResponse {
	this := SubscriptionResponse{}
	return &this
}

// NewSubscriptionResponseWithDefaults instantiates a new SubscriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionResponseWithDefaults() *SubscriptionResponse {
	this := SubscriptionResponse{}
	return &this
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *SubscriptionResponse) SetTier(v string) {
	o.Tier = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetInterval() string {
	if o == nil || IsNil(o.Interval) {
		var ret string
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given string and assigns it to the Interval field.
func (o *SubscriptionResponse) SetInterval(v string) {
	o.Interval = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetPeriodEnd() time.Time {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret time.Time
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetPeriodEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given time.Time and assigns it to the PeriodEnd field.
func (o *SubscriptionResponse) SetPeriodEnd(v time.Time) {
	o.PeriodEnd = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubscriptionResponse) SetStatus(v string) {
	o.Status = &v
}

// GetCreditBalanceCents returns the CreditBalanceCents field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCreditBalanceCents() int32 {
	if o == nil || IsNil(o.CreditBalanceCents) {
		var ret int32
		return ret
	}
	return *o.CreditBalanceCents
}

// GetCreditBalanceCentsOk returns a tuple with the CreditBalanceCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCreditBalanceCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditBalanceCents) {
		return nil, false
	}
	return o.CreditBalanceCents, true
}

// HasCreditBalanceCents returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCreditBalanceCents() bool {
	if o != nil && !IsNil(o.CreditBalanceCents) {
		return true
	}

	return false
}

// SetCreditBalanceCents gets a reference to the given int32 and assigns it to the CreditBalanceCents field.
func (o *SubscriptionResponse) SetCreditBalanceCents(v int32) {
	o.CreditBalanceCents = &v
}

// GetCreditBalanceUsd returns the CreditBalanceUsd field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCreditBalanceUsd() string {
	if o == nil || IsNil(o.CreditBalanceUsd) {
		var ret string
		return ret
	}
	return *o.CreditBalanceUsd
}

// GetCreditBalanceUsdOk returns a tuple with the CreditBalanceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCreditBalanceUsdOk() (*string, bool) {
	if o == nil || IsNil(o.CreditBalanceUsd) {
		return nil, false
	}
	return o.CreditBalanceUsd, true
}

// HasCreditBalanceUsd returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCreditBalanceUsd() bool {
	if o != nil && !IsNil(o.CreditBalanceUsd) {
		return true
	}

	return false
}

// SetCreditBalanceUsd gets a reference to the given string and assigns it to the CreditBalanceUsd field.
func (o *SubscriptionResponse) SetCreditBalanceUsd(v string) {
	o.CreditBalanceUsd = &v
}

// GetOverageMethod returns the OverageMethod field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetOverageMethod() string {
	if o == nil || IsNil(o.OverageMethod) {
		var ret string
		return ret
	}
	return *o.OverageMethod
}

// GetOverageMethodOk returns a tuple with the OverageMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetOverageMethodOk() (*string, bool) {
	if o == nil || IsNil(o.OverageMethod) {
		return nil, false
	}
	return o.OverageMethod, true
}

// HasOverageMethod returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasOverageMethod() bool {
	if o != nil && !IsNil(o.OverageMethod) {
		return true
	}

	return false
}

// SetOverageMethod gets a reference to the given string and assigns it to the OverageMethod field.
func (o *SubscriptionResponse) SetOverageMethod(v string) {
	o.OverageMethod = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetUsage() SubscriptionResponseUsage {
	if o == nil || IsNil(o.Usage) {
		var ret SubscriptionResponseUsage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetUsageOk() (*SubscriptionResponseUsage, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given SubscriptionResponseUsage and assigns it to the Usage field.
func (o *SubscriptionResponse) SetUsage(v SubscriptionResponseUsage) {
	o.Usage = &v
}

func (o SubscriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["period_end"] = o.PeriodEnd
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CreditBalanceCents) {
		toSerialize["credit_balance_cents"] = o.CreditBalanceCents
	}
	if !IsNil(o.CreditBalanceUsd) {
		toSerialize["credit_balance_usd"] = o.CreditBalanceUsd
	}
	if !IsNil(o.OverageMethod) {
		toSerialize["overage_method"] = o.OverageMethod
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableSubscriptionResponse struct {
	value *SubscriptionResponse
	isSet bool
}

func (v NullableSubscriptionResponse) Get() *SubscriptionResponse {
	return v.value
}

func (v *NullableSubscriptionResponse) Set(val *SubscriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionResponse(val *SubscriptionResponse) *NullableSubscriptionResponse {
	return &NullableSubscriptionResponse{value: val, isSet: true}
}

func (v NullableSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


