/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShroudConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShroudConfig{}

// ShroudConfig Per-agent Shroud LLM Proxy configuration
type ShroudConfig struct {
	// How PII detections are handled
	PiiPolicy *string `json:"pii_policy,omitempty"`
	// Prompt injection score threshold (0.0–1.0). Requests above are blocked
	InjectionThreshold *float32 `json:"injection_threshold,omitempty"`
	// Context injection score threshold (0.0–1.0)
	ContextInjectionThreshold *float32 `json:"context_injection_threshold,omitempty"`
	// LLM providers this agent may use (empty = all)
	AllowedProviders []string `json:"allowed_providers,omitempty"`
	// Specific models allowed (empty = all)
	AllowedModels []string `json:"allowed_models,omitempty"`
	// Models explicitly blocked
	DeniedModels []string `json:"denied_models,omitempty"`
	// Maximum input tokens per request
	MaxTokensPerRequest *int32 `json:"max_tokens_per_request,omitempty"`
	// Rate limit (requests per minute)
	MaxRequestsPerMinute *int32 `json:"max_requests_per_minute,omitempty"`
	// Rate limit (requests per day)
	MaxRequestsPerDay *int32 `json:"max_requests_per_day,omitempty"`
	// Daily LLM spend cap in USD (0 = unlimited)
	DailyBudgetUsd *float32 `json:"daily_budget_usd,omitempty"`
	// Whether vault secrets are redacted from prompts/responses
	EnableSecretRedaction *bool `json:"enable_secret_redaction,omitempty"`
	// Whether response credential scanning is active
	EnableResponseFiltering *bool `json:"enable_response_filtering,omitempty"`
	UnicodeNormalization *UnicodeNormalizationConfig `json:"unicode_normalization,omitempty"`
	CommandInjectionDetection *CommandInjectionConfig `json:"command_injection_detection,omitempty"`
	SocialEngineeringDetection *SocialEngineeringConfig `json:"social_engineering_detection,omitempty"`
	EncodingDetection *EncodingDetectionConfig `json:"encoding_detection,omitempty"`
	NetworkDetection *NetworkDetectionConfig `json:"network_detection,omitempty"`
	FilesystemDetection *FilesystemDetectionConfig `json:"filesystem_detection,omitempty"`
	// Global behavior when threats are detected (block=reject, surgical=remove only malicious parts, log_only=audit without action)
	SanitizationMode *string `json:"sanitization_mode,omitempty"`
	// Whether to log all detected threats to audit (even when action is allow/warn)
	ThreatLogging *bool `json:"threat_logging,omitempty"`
}

// NewShroudConfig instantiates a new ShroudConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShroudConfig() *ShroudConfig {
	this := ShroudConfig{}
	var piiPolicy string = "redact"
	this.PiiPolicy = &piiPolicy
	var injectionThreshold float32 = 0.7
	this.InjectionThreshold = &injectionThreshold
	var contextInjectionThreshold float32 = 0.7
	this.ContextInjectionThreshold = &contextInjectionThreshold
	var enableSecretRedaction bool = true
	this.EnableSecretRedaction = &enableSecretRedaction
	var enableResponseFiltering bool = true
	this.EnableResponseFiltering = &enableResponseFiltering
	var sanitizationMode string = "block"
	this.SanitizationMode = &sanitizationMode
	var threatLogging bool = true
	this.ThreatLogging = &threatLogging
	return &this
}

// NewShroudConfigWithDefaults instantiates a new ShroudConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShroudConfigWithDefaults() *ShroudConfig {
	this := ShroudConfig{}
	var piiPolicy string = "redact"
	this.PiiPolicy = &piiPolicy
	var injectionThreshold float32 = 0.7
	this.InjectionThreshold = &injectionThreshold
	var contextInjectionThreshold float32 = 0.7
	this.ContextInjectionThreshold = &contextInjectionThreshold
	var enableSecretRedaction bool = true
	this.EnableSecretRedaction = &enableSecretRedaction
	var enableResponseFiltering bool = true
	this.EnableResponseFiltering = &enableResponseFiltering
	var sanitizationMode string = "block"
	this.SanitizationMode = &sanitizationMode
	var threatLogging bool = true
	this.ThreatLogging = &threatLogging
	return &this
}

// GetPiiPolicy returns the PiiPolicy field value if set, zero value otherwise.
func (o *ShroudConfig) GetPiiPolicy() string {
	if o == nil || IsNil(o.PiiPolicy) {
		var ret string
		return ret
	}
	return *o.PiiPolicy
}

// GetPiiPolicyOk returns a tuple with the PiiPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetPiiPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.PiiPolicy) {
		return nil, false
	}
	return o.PiiPolicy, true
}

// HasPiiPolicy returns a boolean if a field has been set.
func (o *ShroudConfig) HasPiiPolicy() bool {
	if o != nil && !IsNil(o.PiiPolicy) {
		return true
	}

	return false
}

// SetPiiPolicy gets a reference to the given string and assigns it to the PiiPolicy field.
func (o *ShroudConfig) SetPiiPolicy(v string) {
	o.PiiPolicy = &v
}

// GetInjectionThreshold returns the InjectionThreshold field value if set, zero value otherwise.
func (o *ShroudConfig) GetInjectionThreshold() float32 {
	if o == nil || IsNil(o.InjectionThreshold) {
		var ret float32
		return ret
	}
	return *o.InjectionThreshold
}

// GetInjectionThresholdOk returns a tuple with the InjectionThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetInjectionThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.InjectionThreshold) {
		return nil, false
	}
	return o.InjectionThreshold, true
}

// HasInjectionThreshold returns a boolean if a field has been set.
func (o *ShroudConfig) HasInjectionThreshold() bool {
	if o != nil && !IsNil(o.InjectionThreshold) {
		return true
	}

	return false
}

// SetInjectionThreshold gets a reference to the given float32 and assigns it to the InjectionThreshold field.
func (o *ShroudConfig) SetInjectionThreshold(v float32) {
	o.InjectionThreshold = &v
}

// GetContextInjectionThreshold returns the ContextInjectionThreshold field value if set, zero value otherwise.
func (o *ShroudConfig) GetContextInjectionThreshold() float32 {
	if o == nil || IsNil(o.ContextInjectionThreshold) {
		var ret float32
		return ret
	}
	return *o.ContextInjectionThreshold
}

// GetContextInjectionThresholdOk returns a tuple with the ContextInjectionThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetContextInjectionThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.ContextInjectionThreshold) {
		return nil, false
	}
	return o.ContextInjectionThreshold, true
}

// HasContextInjectionThreshold returns a boolean if a field has been set.
func (o *ShroudConfig) HasContextInjectionThreshold() bool {
	if o != nil && !IsNil(o.ContextInjectionThreshold) {
		return true
	}

	return false
}

// SetContextInjectionThreshold gets a reference to the given float32 and assigns it to the ContextInjectionThreshold field.
func (o *ShroudConfig) SetContextInjectionThreshold(v float32) {
	o.ContextInjectionThreshold = &v
}

// GetAllowedProviders returns the AllowedProviders field value if set, zero value otherwise.
func (o *ShroudConfig) GetAllowedProviders() []string {
	if o == nil || IsNil(o.AllowedProviders) {
		var ret []string
		return ret
	}
	return o.AllowedProviders
}

// GetAllowedProvidersOk returns a tuple with the AllowedProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetAllowedProvidersOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedProviders) {
		return nil, false
	}
	return o.AllowedProviders, true
}

// HasAllowedProviders returns a boolean if a field has been set.
func (o *ShroudConfig) HasAllowedProviders() bool {
	if o != nil && !IsNil(o.AllowedProviders) {
		return true
	}

	return false
}

// SetAllowedProviders gets a reference to the given []string and assigns it to the AllowedProviders field.
func (o *ShroudConfig) SetAllowedProviders(v []string) {
	o.AllowedProviders = v
}

// GetAllowedModels returns the AllowedModels field value if set, zero value otherwise.
func (o *ShroudConfig) GetAllowedModels() []string {
	if o == nil || IsNil(o.AllowedModels) {
		var ret []string
		return ret
	}
	return o.AllowedModels
}

// GetAllowedModelsOk returns a tuple with the AllowedModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetAllowedModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedModels) {
		return nil, false
	}
	return o.AllowedModels, true
}

// HasAllowedModels returns a boolean if a field has been set.
func (o *ShroudConfig) HasAllowedModels() bool {
	if o != nil && !IsNil(o.AllowedModels) {
		return true
	}

	return false
}

// SetAllowedModels gets a reference to the given []string and assigns it to the AllowedModels field.
func (o *ShroudConfig) SetAllowedModels(v []string) {
	o.AllowedModels = v
}

// GetDeniedModels returns the DeniedModels field value if set, zero value otherwise.
func (o *ShroudConfig) GetDeniedModels() []string {
	if o == nil || IsNil(o.DeniedModels) {
		var ret []string
		return ret
	}
	return o.DeniedModels
}

// GetDeniedModelsOk returns a tuple with the DeniedModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetDeniedModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.DeniedModels) {
		return nil, false
	}
	return o.DeniedModels, true
}

// HasDeniedModels returns a boolean if a field has been set.
func (o *ShroudConfig) HasDeniedModels() bool {
	if o != nil && !IsNil(o.DeniedModels) {
		return true
	}

	return false
}

// SetDeniedModels gets a reference to the given []string and assigns it to the DeniedModels field.
func (o *ShroudConfig) SetDeniedModels(v []string) {
	o.DeniedModels = v
}

// GetMaxTokensPerRequest returns the MaxTokensPerRequest field value if set, zero value otherwise.
func (o *ShroudConfig) GetMaxTokensPerRequest() int32 {
	if o == nil || IsNil(o.MaxTokensPerRequest) {
		var ret int32
		return ret
	}
	return *o.MaxTokensPerRequest
}

// GetMaxTokensPerRequestOk returns a tuple with the MaxTokensPerRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetMaxTokensPerRequestOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokensPerRequest) {
		return nil, false
	}
	return o.MaxTokensPerRequest, true
}

// HasMaxTokensPerRequest returns a boolean if a field has been set.
func (o *ShroudConfig) HasMaxTokensPerRequest() bool {
	if o != nil && !IsNil(o.MaxTokensPerRequest) {
		return true
	}

	return false
}

// SetMaxTokensPerRequest gets a reference to the given int32 and assigns it to the MaxTokensPerRequest field.
func (o *ShroudConfig) SetMaxTokensPerRequest(v int32) {
	o.MaxTokensPerRequest = &v
}

// GetMaxRequestsPerMinute returns the MaxRequestsPerMinute field value if set, zero value otherwise.
func (o *ShroudConfig) GetMaxRequestsPerMinute() int32 {
	if o == nil || IsNil(o.MaxRequestsPerMinute) {
		var ret int32
		return ret
	}
	return *o.MaxRequestsPerMinute
}

// GetMaxRequestsPerMinuteOk returns a tuple with the MaxRequestsPerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetMaxRequestsPerMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxRequestsPerMinute) {
		return nil, false
	}
	return o.MaxRequestsPerMinute, true
}

// HasMaxRequestsPerMinute returns a boolean if a field has been set.
func (o *ShroudConfig) HasMaxRequestsPerMinute() bool {
	if o != nil && !IsNil(o.MaxRequestsPerMinute) {
		return true
	}

	return false
}

// SetMaxRequestsPerMinute gets a reference to the given int32 and assigns it to the MaxRequestsPerMinute field.
func (o *ShroudConfig) SetMaxRequestsPerMinute(v int32) {
	o.MaxRequestsPerMinute = &v
}

// GetMaxRequestsPerDay returns the MaxRequestsPerDay field value if set, zero value otherwise.
func (o *ShroudConfig) GetMaxRequestsPerDay() int32 {
	if o == nil || IsNil(o.MaxRequestsPerDay) {
		var ret int32
		return ret
	}
	return *o.MaxRequestsPerDay
}

// GetMaxRequestsPerDayOk returns a tuple with the MaxRequestsPerDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetMaxRequestsPerDayOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxRequestsPerDay) {
		return nil, false
	}
	return o.MaxRequestsPerDay, true
}

// HasMaxRequestsPerDay returns a boolean if a field has been set.
func (o *ShroudConfig) HasMaxRequestsPerDay() bool {
	if o != nil && !IsNil(o.MaxRequestsPerDay) {
		return true
	}

	return false
}

// SetMaxRequestsPerDay gets a reference to the given int32 and assigns it to the MaxRequestsPerDay field.
func (o *ShroudConfig) SetMaxRequestsPerDay(v int32) {
	o.MaxRequestsPerDay = &v
}

// GetDailyBudgetUsd returns the DailyBudgetUsd field value if set, zero value otherwise.
func (o *ShroudConfig) GetDailyBudgetUsd() float32 {
	if o == nil || IsNil(o.DailyBudgetUsd) {
		var ret float32
		return ret
	}
	return *o.DailyBudgetUsd
}

// GetDailyBudgetUsdOk returns a tuple with the DailyBudgetUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetDailyBudgetUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.DailyBudgetUsd) {
		return nil, false
	}
	return o.DailyBudgetUsd, true
}

// HasDailyBudgetUsd returns a boolean if a field has been set.
func (o *ShroudConfig) HasDailyBudgetUsd() bool {
	if o != nil && !IsNil(o.DailyBudgetUsd) {
		return true
	}

	return false
}

// SetDailyBudgetUsd gets a reference to the given float32 and assigns it to the DailyBudgetUsd field.
func (o *ShroudConfig) SetDailyBudgetUsd(v float32) {
	o.DailyBudgetUsd = &v
}

// GetEnableSecretRedaction returns the EnableSecretRedaction field value if set, zero value otherwise.
func (o *ShroudConfig) GetEnableSecretRedaction() bool {
	if o == nil || IsNil(o.EnableSecretRedaction) {
		var ret bool
		return ret
	}
	return *o.EnableSecretRedaction
}

// GetEnableSecretRedactionOk returns a tuple with the EnableSecretRedaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetEnableSecretRedactionOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableSecretRedaction) {
		return nil, false
	}
	return o.EnableSecretRedaction, true
}

// HasEnableSecretRedaction returns a boolean if a field has been set.
func (o *ShroudConfig) HasEnableSecretRedaction() bool {
	if o != nil && !IsNil(o.EnableSecretRedaction) {
		return true
	}

	return false
}

// SetEnableSecretRedaction gets a reference to the given bool and assigns it to the EnableSecretRedaction field.
func (o *ShroudConfig) SetEnableSecretRedaction(v bool) {
	o.EnableSecretRedaction = &v
}

// GetEnableResponseFiltering returns the EnableResponseFiltering field value if set, zero value otherwise.
func (o *ShroudConfig) GetEnableResponseFiltering() bool {
	if o == nil || IsNil(o.EnableResponseFiltering) {
		var ret bool
		return ret
	}
	return *o.EnableResponseFiltering
}

// GetEnableResponseFilteringOk returns a tuple with the EnableResponseFiltering field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetEnableResponseFilteringOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableResponseFiltering) {
		return nil, false
	}
	return o.EnableResponseFiltering, true
}

// HasEnableResponseFiltering returns a boolean if a field has been set.
func (o *ShroudConfig) HasEnableResponseFiltering() bool {
	if o != nil && !IsNil(o.EnableResponseFiltering) {
		return true
	}

	return false
}

// SetEnableResponseFiltering gets a reference to the given bool and assigns it to the EnableResponseFiltering field.
func (o *ShroudConfig) SetEnableResponseFiltering(v bool) {
	o.EnableResponseFiltering = &v
}

// GetUnicodeNormalization returns the UnicodeNormalization field value if set, zero value otherwise.
func (o *ShroudConfig) GetUnicodeNormalization() UnicodeNormalizationConfig {
	if o == nil || IsNil(o.UnicodeNormalization) {
		var ret UnicodeNormalizationConfig
		return ret
	}
	return *o.UnicodeNormalization
}

// GetUnicodeNormalizationOk returns a tuple with the UnicodeNormalization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetUnicodeNormalizationOk() (*UnicodeNormalizationConfig, bool) {
	if o == nil || IsNil(o.UnicodeNormalization) {
		return nil, false
	}
	return o.UnicodeNormalization, true
}

// HasUnicodeNormalization returns a boolean if a field has been set.
func (o *ShroudConfig) HasUnicodeNormalization() bool {
	if o != nil && !IsNil(o.UnicodeNormalization) {
		return true
	}

	return false
}

// SetUnicodeNormalization gets a reference to the given UnicodeNormalizationConfig and assigns it to the UnicodeNormalization field.
func (o *ShroudConfig) SetUnicodeNormalization(v UnicodeNormalizationConfig) {
	o.UnicodeNormalization = &v
}

// GetCommandInjectionDetection returns the CommandInjectionDetection field value if set, zero value otherwise.
func (o *ShroudConfig) GetCommandInjectionDetection() CommandInjectionConfig {
	if o == nil || IsNil(o.CommandInjectionDetection) {
		var ret CommandInjectionConfig
		return ret
	}
	return *o.CommandInjectionDetection
}

// GetCommandInjectionDetectionOk returns a tuple with the CommandInjectionDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetCommandInjectionDetectionOk() (*CommandInjectionConfig, bool) {
	if o == nil || IsNil(o.CommandInjectionDetection) {
		return nil, false
	}
	return o.CommandInjectionDetection, true
}

// HasCommandInjectionDetection returns a boolean if a field has been set.
func (o *ShroudConfig) HasCommandInjectionDetection() bool {
	if o != nil && !IsNil(o.CommandInjectionDetection) {
		return true
	}

	return false
}

// SetCommandInjectionDetection gets a reference to the given CommandInjectionConfig and assigns it to the CommandInjectionDetection field.
func (o *ShroudConfig) SetCommandInjectionDetection(v CommandInjectionConfig) {
	o.CommandInjectionDetection = &v
}

// GetSocialEngineeringDetection returns the SocialEngineeringDetection field value if set, zero value otherwise.
func (o *ShroudConfig) GetSocialEngineeringDetection() SocialEngineeringConfig {
	if o == nil || IsNil(o.SocialEngineeringDetection) {
		var ret SocialEngineeringConfig
		return ret
	}
	return *o.SocialEngineeringDetection
}

// GetSocialEngineeringDetectionOk returns a tuple with the SocialEngineeringDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetSocialEngineeringDetectionOk() (*SocialEngineeringConfig, bool) {
	if o == nil || IsNil(o.SocialEngineeringDetection) {
		return nil, false
	}
	return o.SocialEngineeringDetection, true
}

// HasSocialEngineeringDetection returns a boolean if a field has been set.
func (o *ShroudConfig) HasSocialEngineeringDetection() bool {
	if o != nil && !IsNil(o.SocialEngineeringDetection) {
		return true
	}

	return false
}

// SetSocialEngineeringDetection gets a reference to the given SocialEngineeringConfig and assigns it to the SocialEngineeringDetection field.
func (o *ShroudConfig) SetSocialEngineeringDetection(v SocialEngineeringConfig) {
	o.SocialEngineeringDetection = &v
}

// GetEncodingDetection returns the EncodingDetection field value if set, zero value otherwise.
func (o *ShroudConfig) GetEncodingDetection() EncodingDetectionConfig {
	if o == nil || IsNil(o.EncodingDetection) {
		var ret EncodingDetectionConfig
		return ret
	}
	return *o.EncodingDetection
}

// GetEncodingDetectionOk returns a tuple with the EncodingDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetEncodingDetectionOk() (*EncodingDetectionConfig, bool) {
	if o == nil || IsNil(o.EncodingDetection) {
		return nil, false
	}
	return o.EncodingDetection, true
}

// HasEncodingDetection returns a boolean if a field has been set.
func (o *ShroudConfig) HasEncodingDetection() bool {
	if o != nil && !IsNil(o.EncodingDetection) {
		return true
	}

	return false
}

// SetEncodingDetection gets a reference to the given EncodingDetectionConfig and assigns it to the EncodingDetection field.
func (o *ShroudConfig) SetEncodingDetection(v EncodingDetectionConfig) {
	o.EncodingDetection = &v
}

// GetNetworkDetection returns the NetworkDetection field value if set, zero value otherwise.
func (o *ShroudConfig) GetNetworkDetection() NetworkDetectionConfig {
	if o == nil || IsNil(o.NetworkDetection) {
		var ret NetworkDetectionConfig
		return ret
	}
	return *o.NetworkDetection
}

// GetNetworkDetectionOk returns a tuple with the NetworkDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetNetworkDetectionOk() (*NetworkDetectionConfig, bool) {
	if o == nil || IsNil(o.NetworkDetection) {
		return nil, false
	}
	return o.NetworkDetection, true
}

// HasNetworkDetection returns a boolean if a field has been set.
func (o *ShroudConfig) HasNetworkDetection() bool {
	if o != nil && !IsNil(o.NetworkDetection) {
		return true
	}

	return false
}

// SetNetworkDetection gets a reference to the given NetworkDetectionConfig and assigns it to the NetworkDetection field.
func (o *ShroudConfig) SetNetworkDetection(v NetworkDetectionConfig) {
	o.NetworkDetection = &v
}

// GetFilesystemDetection returns the FilesystemDetection field value if set, zero value otherwise.
func (o *ShroudConfig) GetFilesystemDetection() FilesystemDetectionConfig {
	if o == nil || IsNil(o.FilesystemDetection) {
		var ret FilesystemDetectionConfig
		return ret
	}
	return *o.FilesystemDetection
}

// GetFilesystemDetectionOk returns a tuple with the FilesystemDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetFilesystemDetectionOk() (*FilesystemDetectionConfig, bool) {
	if o == nil || IsNil(o.FilesystemDetection) {
		return nil, false
	}
	return o.FilesystemDetection, true
}

// HasFilesystemDetection returns a boolean if a field has been set.
func (o *ShroudConfig) HasFilesystemDetection() bool {
	if o != nil && !IsNil(o.FilesystemDetection) {
		return true
	}

	return false
}

// SetFilesystemDetection gets a reference to the given FilesystemDetectionConfig and assigns it to the FilesystemDetection field.
func (o *ShroudConfig) SetFilesystemDetection(v FilesystemDetectionConfig) {
	o.FilesystemDetection = &v
}

// GetSanitizationMode returns the SanitizationMode field value if set, zero value otherwise.
func (o *ShroudConfig) GetSanitizationMode() string {
	if o == nil || IsNil(o.SanitizationMode) {
		var ret string
		return ret
	}
	return *o.SanitizationMode
}

// GetSanitizationModeOk returns a tuple with the SanitizationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetSanitizationModeOk() (*string, bool) {
	if o == nil || IsNil(o.SanitizationMode) {
		return nil, false
	}
	return o.SanitizationMode, true
}

// HasSanitizationMode returns a boolean if a field has been set.
func (o *ShroudConfig) HasSanitizationMode() bool {
	if o != nil && !IsNil(o.SanitizationMode) {
		return true
	}

	return false
}

// SetSanitizationMode gets a reference to the given string and assigns it to the SanitizationMode field.
func (o *ShroudConfig) SetSanitizationMode(v string) {
	o.SanitizationMode = &v
}

// GetThreatLogging returns the ThreatLogging field value if set, zero value otherwise.
func (o *ShroudConfig) GetThreatLogging() bool {
	if o == nil || IsNil(o.ThreatLogging) {
		var ret bool
		return ret
	}
	return *o.ThreatLogging
}

// GetThreatLoggingOk returns a tuple with the ThreatLogging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShroudConfig) GetThreatLoggingOk() (*bool, bool) {
	if o == nil || IsNil(o.ThreatLogging) {
		return nil, false
	}
	return o.ThreatLogging, true
}

// HasThreatLogging returns a boolean if a field has been set.
func (o *ShroudConfig) HasThreatLogging() bool {
	if o != nil && !IsNil(o.ThreatLogging) {
		return true
	}

	return false
}

// SetThreatLogging gets a reference to the given bool and assigns it to the ThreatLogging field.
func (o *ShroudConfig) SetThreatLogging(v bool) {
	o.ThreatLogging = &v
}

func (o ShroudConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShroudConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PiiPolicy) {
		toSerialize["pii_policy"] = o.PiiPolicy
	}
	if !IsNil(o.InjectionThreshold) {
		toSerialize["injection_threshold"] = o.InjectionThreshold
	}
	if !IsNil(o.ContextInjectionThreshold) {
		toSerialize["context_injection_threshold"] = o.ContextInjectionThreshold
	}
	if !IsNil(o.AllowedProviders) {
		toSerialize["allowed_providers"] = o.AllowedProviders
	}
	if !IsNil(o.AllowedModels) {
		toSerialize["allowed_models"] = o.AllowedModels
	}
	if !IsNil(o.DeniedModels) {
		toSerialize["denied_models"] = o.DeniedModels
	}
	if !IsNil(o.MaxTokensPerRequest) {
		toSerialize["max_tokens_per_request"] = o.MaxTokensPerRequest
	}
	if !IsNil(o.MaxRequestsPerMinute) {
		toSerialize["max_requests_per_minute"] = o.MaxRequestsPerMinute
	}
	if !IsNil(o.MaxRequestsPerDay) {
		toSerialize["max_requests_per_day"] = o.MaxRequestsPerDay
	}
	if !IsNil(o.DailyBudgetUsd) {
		toSerialize["daily_budget_usd"] = o.DailyBudgetUsd
	}
	if !IsNil(o.EnableSecretRedaction) {
		toSerialize["enable_secret_redaction"] = o.EnableSecretRedaction
	}
	if !IsNil(o.EnableResponseFiltering) {
		toSerialize["enable_response_filtering"] = o.EnableResponseFiltering
	}
	if !IsNil(o.UnicodeNormalization) {
		toSerialize["unicode_normalization"] = o.UnicodeNormalization
	}
	if !IsNil(o.CommandInjectionDetection) {
		toSerialize["command_injection_detection"] = o.CommandInjectionDetection
	}
	if !IsNil(o.SocialEngineeringDetection) {
		toSerialize["social_engineering_detection"] = o.SocialEngineeringDetection
	}
	if !IsNil(o.EncodingDetection) {
		toSerialize["encoding_detection"] = o.EncodingDetection
	}
	if !IsNil(o.NetworkDetection) {
		toSerialize["network_detection"] = o.NetworkDetection
	}
	if !IsNil(o.FilesystemDetection) {
		toSerialize["filesystem_detection"] = o.FilesystemDetection
	}
	if !IsNil(o.SanitizationMode) {
		toSerialize["sanitization_mode"] = o.SanitizationMode
	}
	if !IsNil(o.ThreatLogging) {
		toSerialize["threat_logging"] = o.ThreatLogging
	}
	return toSerialize, nil
}

type NullableShroudConfig struct {
	value *ShroudConfig
	isSet bool
}

func (v NullableShroudConfig) Get() *ShroudConfig {
	return v.value
}

func (v *NullableShroudConfig) Set(val *ShroudConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableShroudConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableShroudConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShroudConfig(val *ShroudConfig) *NullableShroudConfig {
	return &NullableShroudConfig{value: val, isSet: true}
}

func (v NullableShroudConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShroudConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


