/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AgentSmartAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentSmartAccountResponse{}

// AgentSmartAccountResponse One Safe smart account per chain for an agent
type AgentSmartAccountResponse struct {
	Id *string `json:"id,omitempty"`
	Chain *string `json:"chain,omitempty"`
	ChainId *int32 `json:"chain_id,omitempty"`
	SafeAddress *string `json:"safe_address,omitempty"`
	Nonce *string `json:"nonce,omitempty"`
	InitData map[string]interface{} `json:"init_data,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAgentSmartAccountResponse instantiates a new AgentSmartAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentSmartAccountResponse() *AgentSmartAccountResponse {
	this := AgentSmartAccountResponse{}
	return &this
}

// NewAgentSmartAccountResponseWithDefaults instantiates a new AgentSmartAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentSmartAccountResponseWithDefaults() *AgentSmartAccountResponse {
	this := AgentSmartAccountResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AgentSmartAccountResponse) SetId(v string) {
	o.Id = &v
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *AgentSmartAccountResponse) SetChain(v string) {
	o.Chain = &v
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetChainId() int32 {
	if o == nil || IsNil(o.ChainId) {
		var ret int32
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetChainIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given int32 and assigns it to the ChainId field.
func (o *AgentSmartAccountResponse) SetChainId(v int32) {
	o.ChainId = &v
}

// GetSafeAddress returns the SafeAddress field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetSafeAddress() string {
	if o == nil || IsNil(o.SafeAddress) {
		var ret string
		return ret
	}
	return *o.SafeAddress
}

// GetSafeAddressOk returns a tuple with the SafeAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetSafeAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SafeAddress) {
		return nil, false
	}
	return o.SafeAddress, true
}

// HasSafeAddress returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasSafeAddress() bool {
	if o != nil && !IsNil(o.SafeAddress) {
		return true
	}

	return false
}

// SetSafeAddress gets a reference to the given string and assigns it to the SafeAddress field.
func (o *AgentSmartAccountResponse) SetSafeAddress(v string) {
	o.SafeAddress = &v
}

// GetNonce returns the Nonce field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetNonce() string {
	if o == nil || IsNil(o.Nonce) {
		var ret string
		return ret
	}
	return *o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetNonceOk() (*string, bool) {
	if o == nil || IsNil(o.Nonce) {
		return nil, false
	}
	return o.Nonce, true
}

// HasNonce returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasNonce() bool {
	if o != nil && !IsNil(o.Nonce) {
		return true
	}

	return false
}

// SetNonce gets a reference to the given string and assigns it to the Nonce field.
func (o *AgentSmartAccountResponse) SetNonce(v string) {
	o.Nonce = &v
}

// GetInitData returns the InitData field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetInitData() map[string]interface{} {
	if o == nil || IsNil(o.InitData) {
		var ret map[string]interface{}
		return ret
	}
	return o.InitData
}

// GetInitDataOk returns a tuple with the InitData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetInitDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InitData) {
		return map[string]interface{}{}, false
	}
	return o.InitData, true
}

// HasInitData returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasInitData() bool {
	if o != nil && !IsNil(o.InitData) {
		return true
	}

	return false
}

// SetInitData gets a reference to the given map[string]interface{} and assigns it to the InitData field.
func (o *AgentSmartAccountResponse) SetInitData(v map[string]interface{}) {
	o.InitData = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentSmartAccountResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentSmartAccountResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentSmartAccountResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AgentSmartAccountResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AgentSmartAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentSmartAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.ChainId) {
		toSerialize["chain_id"] = o.ChainId
	}
	if !IsNil(o.SafeAddress) {
		toSerialize["safe_address"] = o.SafeAddress
	}
	if !IsNil(o.Nonce) {
		toSerialize["nonce"] = o.Nonce
	}
	if !IsNil(o.InitData) {
		toSerialize["init_data"] = o.InitData
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAgentSmartAccountResponse struct {
	value *AgentSmartAccountResponse
	isSet bool
}

func (v NullableAgentSmartAccountResponse) Get() *AgentSmartAccountResponse {
	return v.value
}

func (v *NullableAgentSmartAccountResponse) Set(val *AgentSmartAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentSmartAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentSmartAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentSmartAccountResponse(val *AgentSmartAccountResponse) *NullableAgentSmartAccountResponse {
	return &NullableAgentSmartAccountResponse{value: val, isSet: true}
}

func (v NullableAgentSmartAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentSmartAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


