/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentResponse{}

// AgentResponse struct for AgentResponse
type AgentResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	AuthMethod string `json:"auth_method"`
	Scopes []string `json:"scopes,omitempty"`
	IsActive bool `json:"is_active"`
	IntentsApiEnabled bool `json:"intents_api_enabled"`
	TxToAllowlist []string `json:"tx_to_allowlist,omitempty"`
	TxMaxValueEth *string `json:"tx_max_value_eth,omitempty"`
	TxDailyLimitEth *string `json:"tx_daily_limit_eth,omitempty"`
	TxAllowedChains []string `json:"tx_allowed_chains,omitempty"`
	TokenTtlSeconds *int32 `json:"token_ttl_seconds,omitempty"`
	VaultIds []string `json:"vault_ids,omitempty"`
	// SHA-256 fingerprint of the client certificate (mTLS agents)
	ClientCertFingerprint *string `json:"client_cert_fingerprint,omitempty"`
	// OIDC issuer URL (oidc_client_credentials agents)
	OidcIssuer *string `json:"oidc_issuer,omitempty"`
	// OIDC client ID (oidc_client_credentials agents)
	OidcClientId *string `json:"oidc_client_id,omitempty"`
	// Ed25519 SSH public key (base64-encoded, auto-generated at creation)
	SshPublicKey *string `json:"ssh_public_key,omitempty"`
	// P-256 ECDH public key (base64 SEC1 uncompressed point, auto-generated at creation)
	EcdhPublicKey *string `json:"ecdh_public_key,omitempty"`
	// Whether this agent routes LLM traffic through the Shroud TEE proxy
	ShroudEnabled bool `json:"shroud_enabled"`
	ShroudConfig *ShroudConfig `json:"shroud_config,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	LastActiveAt *time.Time `json:"last_active_at,omitempty"`
	// Multi-chain; one Safe per chain
	SmartAccounts []AgentSmartAccountResponse `json:"smart_accounts,omitempty"`
}

type _AgentResponse AgentResponse

// NewAgentResponse instantiates a new AgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentResponse(id string, name string, authMethod string, isActive bool, intentsApiEnabled bool, shroudEnabled bool, createdAt time.Time) *AgentResponse {
	this := AgentResponse{}
	this.Id = id
	this.Name = name
	this.AuthMethod = authMethod
	this.IsActive = isActive
	this.IntentsApiEnabled = intentsApiEnabled
	this.ShroudEnabled = shroudEnabled
	this.CreatedAt = createdAt
	return &this
}

// NewAgentResponseWithDefaults instantiates a new AgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentResponseWithDefaults() *AgentResponse {
	this := AgentResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AgentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AgentResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentResponse) SetDescription(v string) {
	o.Description = &v
}

// GetAuthMethod returns the AuthMethod field value
func (o *AgentResponse) GetAuthMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthMethod
}

// GetAuthMethodOk returns a tuple with the AuthMethod field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetAuthMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthMethod, true
}

// SetAuthMethod sets field value
func (o *AgentResponse) SetAuthMethod(v string) {
	o.AuthMethod = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AgentResponse) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AgentResponse) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *AgentResponse) SetScopes(v []string) {
	o.Scopes = v
}

// GetIsActive returns the IsActive field value
func (o *AgentResponse) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *AgentResponse) SetIsActive(v bool) {
	o.IsActive = v
}

// GetIntentsApiEnabled returns the IntentsApiEnabled field value
func (o *AgentResponse) GetIntentsApiEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IntentsApiEnabled
}

// GetIntentsApiEnabledOk returns a tuple with the IntentsApiEnabled field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetIntentsApiEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentsApiEnabled, true
}

// SetIntentsApiEnabled sets field value
func (o *AgentResponse) SetIntentsApiEnabled(v bool) {
	o.IntentsApiEnabled = v
}

// GetTxToAllowlist returns the TxToAllowlist field value if set, zero value otherwise.
func (o *AgentResponse) GetTxToAllowlist() []string {
	if o == nil || IsNil(o.TxToAllowlist) {
		var ret []string
		return ret
	}
	return o.TxToAllowlist
}

// GetTxToAllowlistOk returns a tuple with the TxToAllowlist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTxToAllowlistOk() ([]string, bool) {
	if o == nil || IsNil(o.TxToAllowlist) {
		return nil, false
	}
	return o.TxToAllowlist, true
}

// HasTxToAllowlist returns a boolean if a field has been set.
func (o *AgentResponse) HasTxToAllowlist() bool {
	if o != nil && !IsNil(o.TxToAllowlist) {
		return true
	}

	return false
}

// SetTxToAllowlist gets a reference to the given []string and assigns it to the TxToAllowlist field.
func (o *AgentResponse) SetTxToAllowlist(v []string) {
	o.TxToAllowlist = v
}

// GetTxMaxValueEth returns the TxMaxValueEth field value if set, zero value otherwise.
func (o *AgentResponse) GetTxMaxValueEth() string {
	if o == nil || IsNil(o.TxMaxValueEth) {
		var ret string
		return ret
	}
	return *o.TxMaxValueEth
}

// GetTxMaxValueEthOk returns a tuple with the TxMaxValueEth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTxMaxValueEthOk() (*string, bool) {
	if o == nil || IsNil(o.TxMaxValueEth) {
		return nil, false
	}
	return o.TxMaxValueEth, true
}

// HasTxMaxValueEth returns a boolean if a field has been set.
func (o *AgentResponse) HasTxMaxValueEth() bool {
	if o != nil && !IsNil(o.TxMaxValueEth) {
		return true
	}

	return false
}

// SetTxMaxValueEth gets a reference to the given string and assigns it to the TxMaxValueEth field.
func (o *AgentResponse) SetTxMaxValueEth(v string) {
	o.TxMaxValueEth = &v
}

// GetTxDailyLimitEth returns the TxDailyLimitEth field value if set, zero value otherwise.
func (o *AgentResponse) GetTxDailyLimitEth() string {
	if o == nil || IsNil(o.TxDailyLimitEth) {
		var ret string
		return ret
	}
	return *o.TxDailyLimitEth
}

// GetTxDailyLimitEthOk returns a tuple with the TxDailyLimitEth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTxDailyLimitEthOk() (*string, bool) {
	if o == nil || IsNil(o.TxDailyLimitEth) {
		return nil, false
	}
	return o.TxDailyLimitEth, true
}

// HasTxDailyLimitEth returns a boolean if a field has been set.
func (o *AgentResponse) HasTxDailyLimitEth() bool {
	if o != nil && !IsNil(o.TxDailyLimitEth) {
		return true
	}

	return false
}

// SetTxDailyLimitEth gets a reference to the given string and assigns it to the TxDailyLimitEth field.
func (o *AgentResponse) SetTxDailyLimitEth(v string) {
	o.TxDailyLimitEth = &v
}

// GetTxAllowedChains returns the TxAllowedChains field value if set, zero value otherwise.
func (o *AgentResponse) GetTxAllowedChains() []string {
	if o == nil || IsNil(o.TxAllowedChains) {
		var ret []string
		return ret
	}
	return o.TxAllowedChains
}

// GetTxAllowedChainsOk returns a tuple with the TxAllowedChains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTxAllowedChainsOk() ([]string, bool) {
	if o == nil || IsNil(o.TxAllowedChains) {
		return nil, false
	}
	return o.TxAllowedChains, true
}

// HasTxAllowedChains returns a boolean if a field has been set.
func (o *AgentResponse) HasTxAllowedChains() bool {
	if o != nil && !IsNil(o.TxAllowedChains) {
		return true
	}

	return false
}

// SetTxAllowedChains gets a reference to the given []string and assigns it to the TxAllowedChains field.
func (o *AgentResponse) SetTxAllowedChains(v []string) {
	o.TxAllowedChains = v
}

// GetTokenTtlSeconds returns the TokenTtlSeconds field value if set, zero value otherwise.
func (o *AgentResponse) GetTokenTtlSeconds() int32 {
	if o == nil || IsNil(o.TokenTtlSeconds) {
		var ret int32
		return ret
	}
	return *o.TokenTtlSeconds
}

// GetTokenTtlSecondsOk returns a tuple with the TokenTtlSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTokenTtlSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TokenTtlSeconds) {
		return nil, false
	}
	return o.TokenTtlSeconds, true
}

// HasTokenTtlSeconds returns a boolean if a field has been set.
func (o *AgentResponse) HasTokenTtlSeconds() bool {
	if o != nil && !IsNil(o.TokenTtlSeconds) {
		return true
	}

	return false
}

// SetTokenTtlSeconds gets a reference to the given int32 and assigns it to the TokenTtlSeconds field.
func (o *AgentResponse) SetTokenTtlSeconds(v int32) {
	o.TokenTtlSeconds = &v
}

// GetVaultIds returns the VaultIds field value if set, zero value otherwise.
func (o *AgentResponse) GetVaultIds() []string {
	if o == nil || IsNil(o.VaultIds) {
		var ret []string
		return ret
	}
	return o.VaultIds
}

// GetVaultIdsOk returns a tuple with the VaultIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetVaultIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.VaultIds) {
		return nil, false
	}
	return o.VaultIds, true
}

// HasVaultIds returns a boolean if a field has been set.
func (o *AgentResponse) HasVaultIds() bool {
	if o != nil && !IsNil(o.VaultIds) {
		return true
	}

	return false
}

// SetVaultIds gets a reference to the given []string and assigns it to the VaultIds field.
func (o *AgentResponse) SetVaultIds(v []string) {
	o.VaultIds = v
}

// GetClientCertFingerprint returns the ClientCertFingerprint field value if set, zero value otherwise.
func (o *AgentResponse) GetClientCertFingerprint() string {
	if o == nil || IsNil(o.ClientCertFingerprint) {
		var ret string
		return ret
	}
	return *o.ClientCertFingerprint
}

// GetClientCertFingerprintOk returns a tuple with the ClientCertFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetClientCertFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.ClientCertFingerprint) {
		return nil, false
	}
	return o.ClientCertFingerprint, true
}

// HasClientCertFingerprint returns a boolean if a field has been set.
func (o *AgentResponse) HasClientCertFingerprint() bool {
	if o != nil && !IsNil(o.ClientCertFingerprint) {
		return true
	}

	return false
}

// SetClientCertFingerprint gets a reference to the given string and assigns it to the ClientCertFingerprint field.
func (o *AgentResponse) SetClientCertFingerprint(v string) {
	o.ClientCertFingerprint = &v
}

// GetOidcIssuer returns the OidcIssuer field value if set, zero value otherwise.
func (o *AgentResponse) GetOidcIssuer() string {
	if o == nil || IsNil(o.OidcIssuer) {
		var ret string
		return ret
	}
	return *o.OidcIssuer
}

// GetOidcIssuerOk returns a tuple with the OidcIssuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetOidcIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.OidcIssuer) {
		return nil, false
	}
	return o.OidcIssuer, true
}

// HasOidcIssuer returns a boolean if a field has been set.
func (o *AgentResponse) HasOidcIssuer() bool {
	if o != nil && !IsNil(o.OidcIssuer) {
		return true
	}

	return false
}

// SetOidcIssuer gets a reference to the given string and assigns it to the OidcIssuer field.
func (o *AgentResponse) SetOidcIssuer(v string) {
	o.OidcIssuer = &v
}

// GetOidcClientId returns the OidcClientId field value if set, zero value otherwise.
func (o *AgentResponse) GetOidcClientId() string {
	if o == nil || IsNil(o.OidcClientId) {
		var ret string
		return ret
	}
	return *o.OidcClientId
}

// GetOidcClientIdOk returns a tuple with the OidcClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetOidcClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.OidcClientId) {
		return nil, false
	}
	return o.OidcClientId, true
}

// HasOidcClientId returns a boolean if a field has been set.
func (o *AgentResponse) HasOidcClientId() bool {
	if o != nil && !IsNil(o.OidcClientId) {
		return true
	}

	return false
}

// SetOidcClientId gets a reference to the given string and assigns it to the OidcClientId field.
func (o *AgentResponse) SetOidcClientId(v string) {
	o.OidcClientId = &v
}

// GetSshPublicKey returns the SshPublicKey field value if set, zero value otherwise.
func (o *AgentResponse) GetSshPublicKey() string {
	if o == nil || IsNil(o.SshPublicKey) {
		var ret string
		return ret
	}
	return *o.SshPublicKey
}

// GetSshPublicKeyOk returns a tuple with the SshPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetSshPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SshPublicKey) {
		return nil, false
	}
	return o.SshPublicKey, true
}

// HasSshPublicKey returns a boolean if a field has been set.
func (o *AgentResponse) HasSshPublicKey() bool {
	if o != nil && !IsNil(o.SshPublicKey) {
		return true
	}

	return false
}

// SetSshPublicKey gets a reference to the given string and assigns it to the SshPublicKey field.
func (o *AgentResponse) SetSshPublicKey(v string) {
	o.SshPublicKey = &v
}

// GetEcdhPublicKey returns the EcdhPublicKey field value if set, zero value otherwise.
func (o *AgentResponse) GetEcdhPublicKey() string {
	if o == nil || IsNil(o.EcdhPublicKey) {
		var ret string
		return ret
	}
	return *o.EcdhPublicKey
}

// GetEcdhPublicKeyOk returns a tuple with the EcdhPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetEcdhPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.EcdhPublicKey) {
		return nil, false
	}
	return o.EcdhPublicKey, true
}

// HasEcdhPublicKey returns a boolean if a field has been set.
func (o *AgentResponse) HasEcdhPublicKey() bool {
	if o != nil && !IsNil(o.EcdhPublicKey) {
		return true
	}

	return false
}

// SetEcdhPublicKey gets a reference to the given string and assigns it to the EcdhPublicKey field.
func (o *AgentResponse) SetEcdhPublicKey(v string) {
	o.EcdhPublicKey = &v
}

// GetShroudEnabled returns the ShroudEnabled field value
func (o *AgentResponse) GetShroudEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ShroudEnabled
}

// GetShroudEnabledOk returns a tuple with the ShroudEnabled field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetShroudEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShroudEnabled, true
}

// SetShroudEnabled sets field value
func (o *AgentResponse) SetShroudEnabled(v bool) {
	o.ShroudEnabled = v
}

// GetShroudConfig returns the ShroudConfig field value if set, zero value otherwise.
func (o *AgentResponse) GetShroudConfig() ShroudConfig {
	if o == nil || IsNil(o.ShroudConfig) {
		var ret ShroudConfig
		return ret
	}
	return *o.ShroudConfig
}

// GetShroudConfigOk returns a tuple with the ShroudConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetShroudConfigOk() (*ShroudConfig, bool) {
	if o == nil || IsNil(o.ShroudConfig) {
		return nil, false
	}
	return o.ShroudConfig, true
}

// HasShroudConfig returns a boolean if a field has been set.
func (o *AgentResponse) HasShroudConfig() bool {
	if o != nil && !IsNil(o.ShroudConfig) {
		return true
	}

	return false
}

// SetShroudConfig gets a reference to the given ShroudConfig and assigns it to the ShroudConfig field.
func (o *AgentResponse) SetShroudConfig(v ShroudConfig) {
	o.ShroudConfig = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AgentResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AgentResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *AgentResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *AgentResponse) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *AgentResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetLastActiveAt returns the LastActiveAt field value if set, zero value otherwise.
func (o *AgentResponse) GetLastActiveAt() time.Time {
	if o == nil || IsNil(o.LastActiveAt) {
		var ret time.Time
		return ret
	}
	return *o.LastActiveAt
}

// GetLastActiveAtOk returns a tuple with the LastActiveAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetLastActiveAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastActiveAt) {
		return nil, false
	}
	return o.LastActiveAt, true
}

// HasLastActiveAt returns a boolean if a field has been set.
func (o *AgentResponse) HasLastActiveAt() bool {
	if o != nil && !IsNil(o.LastActiveAt) {
		return true
	}

	return false
}

// SetLastActiveAt gets a reference to the given time.Time and assigns it to the LastActiveAt field.
func (o *AgentResponse) SetLastActiveAt(v time.Time) {
	o.LastActiveAt = &v
}

// GetSmartAccounts returns the SmartAccounts field value if set, zero value otherwise.
func (o *AgentResponse) GetSmartAccounts() []AgentSmartAccountResponse {
	if o == nil || IsNil(o.SmartAccounts) {
		var ret []AgentSmartAccountResponse
		return ret
	}
	return o.SmartAccounts
}

// GetSmartAccountsOk returns a tuple with the SmartAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetSmartAccountsOk() ([]AgentSmartAccountResponse, bool) {
	if o == nil || IsNil(o.SmartAccounts) {
		return nil, false
	}
	return o.SmartAccounts, true
}

// HasSmartAccounts returns a boolean if a field has been set.
func (o *AgentResponse) HasSmartAccounts() bool {
	if o != nil && !IsNil(o.SmartAccounts) {
		return true
	}

	return false
}

// SetSmartAccounts gets a reference to the given []AgentSmartAccountResponse and assigns it to the SmartAccounts field.
func (o *AgentResponse) SetSmartAccounts(v []AgentSmartAccountResponse) {
	o.SmartAccounts = v
}

func (o AgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["auth_method"] = o.AuthMethod
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	toSerialize["is_active"] = o.IsActive
	toSerialize["intents_api_enabled"] = o.IntentsApiEnabled
	if !IsNil(o.TxToAllowlist) {
		toSerialize["tx_to_allowlist"] = o.TxToAllowlist
	}
	if !IsNil(o.TxMaxValueEth) {
		toSerialize["tx_max_value_eth"] = o.TxMaxValueEth
	}
	if !IsNil(o.TxDailyLimitEth) {
		toSerialize["tx_daily_limit_eth"] = o.TxDailyLimitEth
	}
	if !IsNil(o.TxAllowedChains) {
		toSerialize["tx_allowed_chains"] = o.TxAllowedChains
	}
	if !IsNil(o.TokenTtlSeconds) {
		toSerialize["token_ttl_seconds"] = o.TokenTtlSeconds
	}
	if !IsNil(o.VaultIds) {
		toSerialize["vault_ids"] = o.VaultIds
	}
	if !IsNil(o.ClientCertFingerprint) {
		toSerialize["client_cert_fingerprint"] = o.ClientCertFingerprint
	}
	if !IsNil(o.OidcIssuer) {
		toSerialize["oidc_issuer"] = o.OidcIssuer
	}
	if !IsNil(o.OidcClientId) {
		toSerialize["oidc_client_id"] = o.OidcClientId
	}
	if !IsNil(o.SshPublicKey) {
		toSerialize["ssh_public_key"] = o.SshPublicKey
	}
	if !IsNil(o.EcdhPublicKey) {
		toSerialize["ecdh_public_key"] = o.EcdhPublicKey
	}
	toSerialize["shroud_enabled"] = o.ShroudEnabled
	if !IsNil(o.ShroudConfig) {
		toSerialize["shroud_config"] = o.ShroudConfig
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.LastActiveAt) {
		toSerialize["last_active_at"] = o.LastActiveAt
	}
	if !IsNil(o.SmartAccounts) {
		toSerialize["smart_accounts"] = o.SmartAccounts
	}
	return toSerialize, nil
}

func (o *AgentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"auth_method",
		"is_active",
		"intents_api_enabled",
		"shroud_enabled",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentResponse := _AgentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentResponse)

	if err != nil {
		return err
	}

	*o = AgentResponse(varAgentResponse)

	return err
}

type NullableAgentResponse struct {
	value *AgentResponse
	isSet bool
}

func (v NullableAgentResponse) Get() *AgentResponse {
	return v.value
}

func (v *NullableAgentResponse) Set(val *AgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentResponse(val *AgentResponse) *NullableAgentResponse {
	return &NullableAgentResponse{value: val, isSet: true}
}

func (v NullableAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


