/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubscriptionResponseUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionResponseUsage{}

// SubscriptionResponseUsage struct for SubscriptionResponseUsage
type SubscriptionResponseUsage struct {
	Requests *UsageMeter `json:"requests,omitempty"`
	Secrets *UsageMeter `json:"secrets,omitempty"`
	Agents *UsageMeter `json:"agents,omitempty"`
	Vaults *UsageMeter `json:"vaults,omitempty"`
	TeamMembers *UsageMeter `json:"team_members,omitempty"`
	IntentTransactions *UsageMeter `json:"intent_transactions,omitempty"`
	Shares *UsageMeter `json:"shares,omitempty"`
}

// NewSubscriptionResponseUsage instantiates a new SubscriptionResponseUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionResponseUsage() *SubscriptionResponseUsage {
	this := SubscriptionResponseUsage{}
	return &this
}

// NewSubscriptionResponseUsageWithDefaults instantiates a new SubscriptionResponseUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionResponseUsageWithDefaults() *SubscriptionResponseUsage {
	this := SubscriptionResponseUsage{}
	return &this
}

// GetRequests returns the Requests field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetRequests() UsageMeter {
	if o == nil || IsNil(o.Requests) {
		var ret UsageMeter
		return ret
	}
	return *o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetRequestsOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.Requests) {
		return nil, false
	}
	return o.Requests, true
}

// HasRequests returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasRequests() bool {
	if o != nil && !IsNil(o.Requests) {
		return true
	}

	return false
}

// SetRequests gets a reference to the given UsageMeter and assigns it to the Requests field.
func (o *SubscriptionResponseUsage) SetRequests(v UsageMeter) {
	o.Requests = &v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetSecrets() UsageMeter {
	if o == nil || IsNil(o.Secrets) {
		var ret UsageMeter
		return ret
	}
	return *o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetSecretsOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given UsageMeter and assigns it to the Secrets field.
func (o *SubscriptionResponseUsage) SetSecrets(v UsageMeter) {
	o.Secrets = &v
}

// GetAgents returns the Agents field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetAgents() UsageMeter {
	if o == nil || IsNil(o.Agents) {
		var ret UsageMeter
		return ret
	}
	return *o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetAgentsOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.Agents) {
		return nil, false
	}
	return o.Agents, true
}

// HasAgents returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasAgents() bool {
	if o != nil && !IsNil(o.Agents) {
		return true
	}

	return false
}

// SetAgents gets a reference to the given UsageMeter and assigns it to the Agents field.
func (o *SubscriptionResponseUsage) SetAgents(v UsageMeter) {
	o.Agents = &v
}

// GetVaults returns the Vaults field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetVaults() UsageMeter {
	if o == nil || IsNil(o.Vaults) {
		var ret UsageMeter
		return ret
	}
	return *o.Vaults
}

// GetVaultsOk returns a tuple with the Vaults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetVaultsOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.Vaults) {
		return nil, false
	}
	return o.Vaults, true
}

// HasVaults returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasVaults() bool {
	if o != nil && !IsNil(o.Vaults) {
		return true
	}

	return false
}

// SetVaults gets a reference to the given UsageMeter and assigns it to the Vaults field.
func (o *SubscriptionResponseUsage) SetVaults(v UsageMeter) {
	o.Vaults = &v
}

// GetTeamMembers returns the TeamMembers field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetTeamMembers() UsageMeter {
	if o == nil || IsNil(o.TeamMembers) {
		var ret UsageMeter
		return ret
	}
	return *o.TeamMembers
}

// GetTeamMembersOk returns a tuple with the TeamMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetTeamMembersOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.TeamMembers) {
		return nil, false
	}
	return o.TeamMembers, true
}

// HasTeamMembers returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasTeamMembers() bool {
	if o != nil && !IsNil(o.TeamMembers) {
		return true
	}

	return false
}

// SetTeamMembers gets a reference to the given UsageMeter and assigns it to the TeamMembers field.
func (o *SubscriptionResponseUsage) SetTeamMembers(v UsageMeter) {
	o.TeamMembers = &v
}

// GetIntentTransactions returns the IntentTransactions field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetIntentTransactions() UsageMeter {
	if o == nil || IsNil(o.IntentTransactions) {
		var ret UsageMeter
		return ret
	}
	return *o.IntentTransactions
}

// GetIntentTransactionsOk returns a tuple with the IntentTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetIntentTransactionsOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.IntentTransactions) {
		return nil, false
	}
	return o.IntentTransactions, true
}

// HasIntentTransactions returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasIntentTransactions() bool {
	if o != nil && !IsNil(o.IntentTransactions) {
		return true
	}

	return false
}

// SetIntentTransactions gets a reference to the given UsageMeter and assigns it to the IntentTransactions field.
func (o *SubscriptionResponseUsage) SetIntentTransactions(v UsageMeter) {
	o.IntentTransactions = &v
}

// GetShares returns the Shares field value if set, zero value otherwise.
func (o *SubscriptionResponseUsage) GetShares() UsageMeter {
	if o == nil || IsNil(o.Shares) {
		var ret UsageMeter
		return ret
	}
	return *o.Shares
}

// GetSharesOk returns a tuple with the Shares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponseUsage) GetSharesOk() (*UsageMeter, bool) {
	if o == nil || IsNil(o.Shares) {
		return nil, false
	}
	return o.Shares, true
}

// HasShares returns a boolean if a field has been set.
func (o *SubscriptionResponseUsage) HasShares() bool {
	if o != nil && !IsNil(o.Shares) {
		return true
	}

	return false
}

// SetShares gets a reference to the given UsageMeter and assigns it to the Shares field.
func (o *SubscriptionResponseUsage) SetShares(v UsageMeter) {
	o.Shares = &v
}

func (o SubscriptionResponseUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionResponseUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requests) {
		toSerialize["requests"] = o.Requests
	}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	if !IsNil(o.Agents) {
		toSerialize["agents"] = o.Agents
	}
	if !IsNil(o.Vaults) {
		toSerialize["vaults"] = o.Vaults
	}
	if !IsNil(o.TeamMembers) {
		toSerialize["team_members"] = o.TeamMembers
	}
	if !IsNil(o.IntentTransactions) {
		toSerialize["intent_transactions"] = o.IntentTransactions
	}
	if !IsNil(o.Shares) {
		toSerialize["shares"] = o.Shares
	}
	return toSerialize, nil
}

type NullableSubscriptionResponseUsage struct {
	value *SubscriptionResponseUsage
	isSet bool
}

func (v NullableSubscriptionResponseUsage) Get() *SubscriptionResponseUsage {
	return v.value
}

func (v *NullableSubscriptionResponseUsage) Set(val *SubscriptionResponseUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionResponseUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionResponseUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionResponseUsage(val *SubscriptionResponseUsage) *NullableSubscriptionResponseUsage {
	return &NullableSubscriptionResponseUsage{value: val, isSet: true}
}

func (v NullableSubscriptionResponseUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionResponseUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


