/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSettingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSettingRequest{}

// UpdateSettingRequest struct for UpdateSettingRequest
type UpdateSettingRequest struct {
	Value string `json:"value"`
}

type _UpdateSettingRequest UpdateSettingRequest

// NewUpdateSettingRequest instantiates a new UpdateSettingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSettingRequest(value string) *UpdateSettingRequest {
	this := UpdateSettingRequest{}
	this.Value = value
	return &this
}

// NewUpdateSettingRequestWithDefaults instantiates a new UpdateSettingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSettingRequestWithDefaults() *UpdateSettingRequest {
	this := UpdateSettingRequest{}
	return &this
}

// GetValue returns the Value field value
func (o *UpdateSettingRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UpdateSettingRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *UpdateSettingRequest) SetValue(v string) {
	o.Value = v
}

func (o UpdateSettingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSettingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *UpdateSettingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSettingRequest := _UpdateSettingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSettingRequest)

	if err != nil {
		return err
	}

	*o = UpdateSettingRequest(varUpdateSettingRequest)

	return err
}

type NullableUpdateSettingRequest struct {
	value *UpdateSettingRequest
	isSet bool
}

func (v NullableUpdateSettingRequest) Get() *UpdateSettingRequest {
	return v.value
}

func (v *NullableUpdateSettingRequest) Set(val *UpdateSettingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSettingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSettingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSettingRequest(val *UpdateSettingRequest) *NullableUpdateSettingRequest {
	return &NullableUpdateSettingRequest{value: val, isSet: true}
}

func (v NullableUpdateSettingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSettingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


