/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UnicodeNormalizationConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnicodeNormalizationConfig{}

// UnicodeNormalizationConfig Unicode normalization and homoglyph detection settings
type UnicodeNormalizationConfig struct {
	// Enable Unicode normalization
	Enabled *bool `json:"enabled,omitempty"`
	// Remove zero-width and invisible Unicode characters
	StripZeroWidth *bool `json:"strip_zero_width,omitempty"`
	// Replace look-alike characters (e.g., Cyrillic а → Latin a)
	NormalizeHomoglyphs *bool `json:"normalize_homoglyphs,omitempty"`
	// Unicode normalization form to apply
	NormalizationForm *string `json:"normalization_form,omitempty"`
}

// NewUnicodeNormalizationConfig instantiates a new UnicodeNormalizationConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnicodeNormalizationConfig() *UnicodeNormalizationConfig {
	this := UnicodeNormalizationConfig{}
	var enabled bool = true
	this.Enabled = &enabled
	var stripZeroWidth bool = true
	this.StripZeroWidth = &stripZeroWidth
	var normalizeHomoglyphs bool = true
	this.NormalizeHomoglyphs = &normalizeHomoglyphs
	var normalizationForm string = "NFKC"
	this.NormalizationForm = &normalizationForm
	return &this
}

// NewUnicodeNormalizationConfigWithDefaults instantiates a new UnicodeNormalizationConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnicodeNormalizationConfigWithDefaults() *UnicodeNormalizationConfig {
	this := UnicodeNormalizationConfig{}
	var enabled bool = true
	this.Enabled = &enabled
	var stripZeroWidth bool = true
	this.StripZeroWidth = &stripZeroWidth
	var normalizeHomoglyphs bool = true
	this.NormalizeHomoglyphs = &normalizeHomoglyphs
	var normalizationForm string = "NFKC"
	this.NormalizationForm = &normalizationForm
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *UnicodeNormalizationConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnicodeNormalizationConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *UnicodeNormalizationConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *UnicodeNormalizationConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetStripZeroWidth returns the StripZeroWidth field value if set, zero value otherwise.
func (o *UnicodeNormalizationConfig) GetStripZeroWidth() bool {
	if o == nil || IsNil(o.StripZeroWidth) {
		var ret bool
		return ret
	}
	return *o.StripZeroWidth
}

// GetStripZeroWidthOk returns a tuple with the StripZeroWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnicodeNormalizationConfig) GetStripZeroWidthOk() (*bool, bool) {
	if o == nil || IsNil(o.StripZeroWidth) {
		return nil, false
	}
	return o.StripZeroWidth, true
}

// HasStripZeroWidth returns a boolean if a field has been set.
func (o *UnicodeNormalizationConfig) HasStripZeroWidth() bool {
	if o != nil && !IsNil(o.StripZeroWidth) {
		return true
	}

	return false
}

// SetStripZeroWidth gets a reference to the given bool and assigns it to the StripZeroWidth field.
func (o *UnicodeNormalizationConfig) SetStripZeroWidth(v bool) {
	o.StripZeroWidth = &v
}

// GetNormalizeHomoglyphs returns the NormalizeHomoglyphs field value if set, zero value otherwise.
func (o *UnicodeNormalizationConfig) GetNormalizeHomoglyphs() bool {
	if o == nil || IsNil(o.NormalizeHomoglyphs) {
		var ret bool
		return ret
	}
	return *o.NormalizeHomoglyphs
}

// GetNormalizeHomoglyphsOk returns a tuple with the NormalizeHomoglyphs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnicodeNormalizationConfig) GetNormalizeHomoglyphsOk() (*bool, bool) {
	if o == nil || IsNil(o.NormalizeHomoglyphs) {
		return nil, false
	}
	return o.NormalizeHomoglyphs, true
}

// HasNormalizeHomoglyphs returns a boolean if a field has been set.
func (o *UnicodeNormalizationConfig) HasNormalizeHomoglyphs() bool {
	if o != nil && !IsNil(o.NormalizeHomoglyphs) {
		return true
	}

	return false
}

// SetNormalizeHomoglyphs gets a reference to the given bool and assigns it to the NormalizeHomoglyphs field.
func (o *UnicodeNormalizationConfig) SetNormalizeHomoglyphs(v bool) {
	o.NormalizeHomoglyphs = &v
}

// GetNormalizationForm returns the NormalizationForm field value if set, zero value otherwise.
func (o *UnicodeNormalizationConfig) GetNormalizationForm() string {
	if o == nil || IsNil(o.NormalizationForm) {
		var ret string
		return ret
	}
	return *o.NormalizationForm
}

// GetNormalizationFormOk returns a tuple with the NormalizationForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnicodeNormalizationConfig) GetNormalizationFormOk() (*string, bool) {
	if o == nil || IsNil(o.NormalizationForm) {
		return nil, false
	}
	return o.NormalizationForm, true
}

// HasNormalizationForm returns a boolean if a field has been set.
func (o *UnicodeNormalizationConfig) HasNormalizationForm() bool {
	if o != nil && !IsNil(o.NormalizationForm) {
		return true
	}

	return false
}

// SetNormalizationForm gets a reference to the given string and assigns it to the NormalizationForm field.
func (o *UnicodeNormalizationConfig) SetNormalizationForm(v string) {
	o.NormalizationForm = &v
}

func (o UnicodeNormalizationConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnicodeNormalizationConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.StripZeroWidth) {
		toSerialize["strip_zero_width"] = o.StripZeroWidth
	}
	if !IsNil(o.NormalizeHomoglyphs) {
		toSerialize["normalize_homoglyphs"] = o.NormalizeHomoglyphs
	}
	if !IsNil(o.NormalizationForm) {
		toSerialize["normalization_form"] = o.NormalizationForm
	}
	return toSerialize, nil
}

type NullableUnicodeNormalizationConfig struct {
	value *UnicodeNormalizationConfig
	isSet bool
}

func (v NullableUnicodeNormalizationConfig) Get() *UnicodeNormalizationConfig {
	return v.value
}

func (v *NullableUnicodeNormalizationConfig) Set(val *UnicodeNormalizationConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUnicodeNormalizationConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUnicodeNormalizationConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnicodeNormalizationConfig(val *UnicodeNormalizationConfig) *NullableUnicodeNormalizationConfig {
	return &NullableUnicodeNormalizationConfig{value: val, isSet: true}
}

func (v NullableUnicodeNormalizationConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnicodeNormalizationConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


