/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoogleAuthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleAuthRequest{}

// GoogleAuthRequest struct for GoogleAuthRequest
type GoogleAuthRequest struct {
	IdToken string `json:"id_token"`
}

type _GoogleAuthRequest GoogleAuthRequest

// NewGoogleAuthRequest instantiates a new GoogleAuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleAuthRequest(idToken string) *GoogleAuthRequest {
	this := GoogleAuthRequest{}
	this.IdToken = idToken
	return &this
}

// NewGoogleAuthRequestWithDefaults instantiates a new GoogleAuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleAuthRequestWithDefaults() *GoogleAuthRequest {
	this := GoogleAuthRequest{}
	return &this
}

// GetIdToken returns the IdToken field value
func (o *GoogleAuthRequest) GetIdToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdToken
}

// GetIdTokenOk returns a tuple with the IdToken field value
// and a boolean to check if the value has been set.
func (o *GoogleAuthRequest) GetIdTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdToken, true
}

// SetIdToken sets field value
func (o *GoogleAuthRequest) SetIdToken(v string) {
	o.IdToken = v
}

func (o GoogleAuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleAuthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id_token"] = o.IdToken
	return toSerialize, nil
}

func (o *GoogleAuthRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoogleAuthRequest := _GoogleAuthRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoogleAuthRequest)

	if err != nil {
		return err
	}

	*o = GoogleAuthRequest(varGoogleAuthRequest)

	return err
}

type NullableGoogleAuthRequest struct {
	value *GoogleAuthRequest
	isSet bool
}

func (v NullableGoogleAuthRequest) Get() *GoogleAuthRequest {
	return v.value
}

func (v *NullableGoogleAuthRequest) Set(val *GoogleAuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleAuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleAuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleAuthRequest(val *GoogleAuthRequest) *NullableGoogleAuthRequest {
	return &NullableGoogleAuthRequest{value: val, isSet: true}
}

func (v NullableGoogleAuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleAuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


