/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateShareRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShareRequest{}

// CreateShareRequest struct for CreateShareRequest
type CreateShareRequest struct {
	RecipientType string `json:"recipient_type"`
	RecipientId *string `json:"recipient_id,omitempty"`
	Email *string `json:"email,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
	MaxAccessCount *int32 `json:"max_access_count,omitempty"`
	ExpiresAt time.Time `json:"expires_at"`
	Passphrase *string `json:"passphrase,omitempty"`
	IpAllowlist []string `json:"ip_allowlist,omitempty"`
}

type _CreateShareRequest CreateShareRequest

// NewCreateShareRequest instantiates a new CreateShareRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShareRequest(recipientType string, expiresAt time.Time) *CreateShareRequest {
	this := CreateShareRequest{}
	this.RecipientType = recipientType
	this.ExpiresAt = expiresAt
	return &this
}

// NewCreateShareRequestWithDefaults instantiates a new CreateShareRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShareRequestWithDefaults() *CreateShareRequest {
	this := CreateShareRequest{}
	return &this
}

// GetRecipientType returns the RecipientType field value
func (o *CreateShareRequest) GetRecipientType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientType
}

// GetRecipientTypeOk returns a tuple with the RecipientType field value
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetRecipientTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientType, true
}

// SetRecipientType sets field value
func (o *CreateShareRequest) SetRecipientType(v string) {
	o.RecipientType = v
}

// GetRecipientId returns the RecipientId field value if set, zero value otherwise.
func (o *CreateShareRequest) GetRecipientId() string {
	if o == nil || IsNil(o.RecipientId) {
		var ret string
		return ret
	}
	return *o.RecipientId
}

// GetRecipientIdOk returns a tuple with the RecipientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetRecipientIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientId) {
		return nil, false
	}
	return o.RecipientId, true
}

// HasRecipientId returns a boolean if a field has been set.
func (o *CreateShareRequest) HasRecipientId() bool {
	if o != nil && !IsNil(o.RecipientId) {
		return true
	}

	return false
}

// SetRecipientId gets a reference to the given string and assigns it to the RecipientId field.
func (o *CreateShareRequest) SetRecipientId(v string) {
	o.RecipientId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateShareRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateShareRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateShareRequest) SetEmail(v string) {
	o.Email = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *CreateShareRequest) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *CreateShareRequest) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *CreateShareRequest) SetPermissions(v []string) {
	o.Permissions = v
}

// GetMaxAccessCount returns the MaxAccessCount field value if set, zero value otherwise.
func (o *CreateShareRequest) GetMaxAccessCount() int32 {
	if o == nil || IsNil(o.MaxAccessCount) {
		var ret int32
		return ret
	}
	return *o.MaxAccessCount
}

// GetMaxAccessCountOk returns a tuple with the MaxAccessCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetMaxAccessCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxAccessCount) {
		return nil, false
	}
	return o.MaxAccessCount, true
}

// HasMaxAccessCount returns a boolean if a field has been set.
func (o *CreateShareRequest) HasMaxAccessCount() bool {
	if o != nil && !IsNil(o.MaxAccessCount) {
		return true
	}

	return false
}

// SetMaxAccessCount gets a reference to the given int32 and assigns it to the MaxAccessCount field.
func (o *CreateShareRequest) SetMaxAccessCount(v int32) {
	o.MaxAccessCount = &v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CreateShareRequest) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CreateShareRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetPassphrase returns the Passphrase field value if set, zero value otherwise.
func (o *CreateShareRequest) GetPassphrase() string {
	if o == nil || IsNil(o.Passphrase) {
		var ret string
		return ret
	}
	return *o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetPassphraseOk() (*string, bool) {
	if o == nil || IsNil(o.Passphrase) {
		return nil, false
	}
	return o.Passphrase, true
}

// HasPassphrase returns a boolean if a field has been set.
func (o *CreateShareRequest) HasPassphrase() bool {
	if o != nil && !IsNil(o.Passphrase) {
		return true
	}

	return false
}

// SetPassphrase gets a reference to the given string and assigns it to the Passphrase field.
func (o *CreateShareRequest) SetPassphrase(v string) {
	o.Passphrase = &v
}

// GetIpAllowlist returns the IpAllowlist field value if set, zero value otherwise.
func (o *CreateShareRequest) GetIpAllowlist() []string {
	if o == nil || IsNil(o.IpAllowlist) {
		var ret []string
		return ret
	}
	return o.IpAllowlist
}

// GetIpAllowlistOk returns a tuple with the IpAllowlist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShareRequest) GetIpAllowlistOk() ([]string, bool) {
	if o == nil || IsNil(o.IpAllowlist) {
		return nil, false
	}
	return o.IpAllowlist, true
}

// HasIpAllowlist returns a boolean if a field has been set.
func (o *CreateShareRequest) HasIpAllowlist() bool {
	if o != nil && !IsNil(o.IpAllowlist) {
		return true
	}

	return false
}

// SetIpAllowlist gets a reference to the given []string and assigns it to the IpAllowlist field.
func (o *CreateShareRequest) SetIpAllowlist(v []string) {
	o.IpAllowlist = v
}

func (o CreateShareRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShareRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recipient_type"] = o.RecipientType
	if !IsNil(o.RecipientId) {
		toSerialize["recipient_id"] = o.RecipientId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.MaxAccessCount) {
		toSerialize["max_access_count"] = o.MaxAccessCount
	}
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.Passphrase) {
		toSerialize["passphrase"] = o.Passphrase
	}
	if !IsNil(o.IpAllowlist) {
		toSerialize["ip_allowlist"] = o.IpAllowlist
	}
	return toSerialize, nil
}

func (o *CreateShareRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipient_type",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShareRequest := _CreateShareRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShareRequest)

	if err != nil {
		return err
	}

	*o = CreateShareRequest(varCreateShareRequest)

	return err
}

type NullableCreateShareRequest struct {
	value *CreateShareRequest
	isSet bool
}

func (v NullableCreateShareRequest) Get() *CreateShareRequest {
	return v.value
}

func (v *NullableCreateShareRequest) Set(val *CreateShareRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShareRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShareRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShareRequest(val *CreateShareRequest) *NullableCreateShareRequest {
	return &NullableCreateShareRequest{value: val, isSet: true}
}

func (v NullableCreateShareRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShareRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


