/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateChainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateChainRequest{}

// CreateChainRequest struct for CreateChainRequest
type CreateChainRequest struct {
	Name string `json:"name"`
	DisplayName string `json:"display_name"`
	ChainId int32 `json:"chain_id"`
	RpcUrl *string `json:"rpc_url,omitempty"`
	WsUrl *string `json:"ws_url,omitempty"`
	ExplorerUrl *string `json:"explorer_url,omitempty"`
	NativeCurrency *string `json:"native_currency,omitempty"`
	IsTestnet *bool `json:"is_testnet,omitempty"`
	IsEnabled *bool `json:"is_enabled,omitempty"`
}

type _CreateChainRequest CreateChainRequest

// NewCreateChainRequest instantiates a new CreateChainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateChainRequest(name string, displayName string, chainId int32) *CreateChainRequest {
	this := CreateChainRequest{}
	this.Name = name
	this.DisplayName = displayName
	this.ChainId = chainId
	var nativeCurrency string = "ETH"
	this.NativeCurrency = &nativeCurrency
	var isTestnet bool = false
	this.IsTestnet = &isTestnet
	var isEnabled bool = true
	this.IsEnabled = &isEnabled
	return &this
}

// NewCreateChainRequestWithDefaults instantiates a new CreateChainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateChainRequestWithDefaults() *CreateChainRequest {
	this := CreateChainRequest{}
	var nativeCurrency string = "ETH"
	this.NativeCurrency = &nativeCurrency
	var isTestnet bool = false
	this.IsTestnet = &isTestnet
	var isEnabled bool = true
	this.IsEnabled = &isEnabled
	return &this
}

// GetName returns the Name field value
func (o *CreateChainRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateChainRequest) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *CreateChainRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CreateChainRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetChainId returns the ChainId field value
func (o *CreateChainRequest) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *CreateChainRequest) SetChainId(v int32) {
	o.ChainId = v
}

// GetRpcUrl returns the RpcUrl field value if set, zero value otherwise.
func (o *CreateChainRequest) GetRpcUrl() string {
	if o == nil || IsNil(o.RpcUrl) {
		var ret string
		return ret
	}
	return *o.RpcUrl
}

// GetRpcUrlOk returns a tuple with the RpcUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetRpcUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RpcUrl) {
		return nil, false
	}
	return o.RpcUrl, true
}

// HasRpcUrl returns a boolean if a field has been set.
func (o *CreateChainRequest) HasRpcUrl() bool {
	if o != nil && !IsNil(o.RpcUrl) {
		return true
	}

	return false
}

// SetRpcUrl gets a reference to the given string and assigns it to the RpcUrl field.
func (o *CreateChainRequest) SetRpcUrl(v string) {
	o.RpcUrl = &v
}

// GetWsUrl returns the WsUrl field value if set, zero value otherwise.
func (o *CreateChainRequest) GetWsUrl() string {
	if o == nil || IsNil(o.WsUrl) {
		var ret string
		return ret
	}
	return *o.WsUrl
}

// GetWsUrlOk returns a tuple with the WsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetWsUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WsUrl) {
		return nil, false
	}
	return o.WsUrl, true
}

// HasWsUrl returns a boolean if a field has been set.
func (o *CreateChainRequest) HasWsUrl() bool {
	if o != nil && !IsNil(o.WsUrl) {
		return true
	}

	return false
}

// SetWsUrl gets a reference to the given string and assigns it to the WsUrl field.
func (o *CreateChainRequest) SetWsUrl(v string) {
	o.WsUrl = &v
}

// GetExplorerUrl returns the ExplorerUrl field value if set, zero value otherwise.
func (o *CreateChainRequest) GetExplorerUrl() string {
	if o == nil || IsNil(o.ExplorerUrl) {
		var ret string
		return ret
	}
	return *o.ExplorerUrl
}

// GetExplorerUrlOk returns a tuple with the ExplorerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetExplorerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ExplorerUrl) {
		return nil, false
	}
	return o.ExplorerUrl, true
}

// HasExplorerUrl returns a boolean if a field has been set.
func (o *CreateChainRequest) HasExplorerUrl() bool {
	if o != nil && !IsNil(o.ExplorerUrl) {
		return true
	}

	return false
}

// SetExplorerUrl gets a reference to the given string and assigns it to the ExplorerUrl field.
func (o *CreateChainRequest) SetExplorerUrl(v string) {
	o.ExplorerUrl = &v
}

// GetNativeCurrency returns the NativeCurrency field value if set, zero value otherwise.
func (o *CreateChainRequest) GetNativeCurrency() string {
	if o == nil || IsNil(o.NativeCurrency) {
		var ret string
		return ret
	}
	return *o.NativeCurrency
}

// GetNativeCurrencyOk returns a tuple with the NativeCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetNativeCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.NativeCurrency) {
		return nil, false
	}
	return o.NativeCurrency, true
}

// HasNativeCurrency returns a boolean if a field has been set.
func (o *CreateChainRequest) HasNativeCurrency() bool {
	if o != nil && !IsNil(o.NativeCurrency) {
		return true
	}

	return false
}

// SetNativeCurrency gets a reference to the given string and assigns it to the NativeCurrency field.
func (o *CreateChainRequest) SetNativeCurrency(v string) {
	o.NativeCurrency = &v
}

// GetIsTestnet returns the IsTestnet field value if set, zero value otherwise.
func (o *CreateChainRequest) GetIsTestnet() bool {
	if o == nil || IsNil(o.IsTestnet) {
		var ret bool
		return ret
	}
	return *o.IsTestnet
}

// GetIsTestnetOk returns a tuple with the IsTestnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetIsTestnetOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTestnet) {
		return nil, false
	}
	return o.IsTestnet, true
}

// HasIsTestnet returns a boolean if a field has been set.
func (o *CreateChainRequest) HasIsTestnet() bool {
	if o != nil && !IsNil(o.IsTestnet) {
		return true
	}

	return false
}

// SetIsTestnet gets a reference to the given bool and assigns it to the IsTestnet field.
func (o *CreateChainRequest) SetIsTestnet(v bool) {
	o.IsTestnet = &v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *CreateChainRequest) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateChainRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *CreateChainRequest) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *CreateChainRequest) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

func (o CreateChainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateChainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["display_name"] = o.DisplayName
	toSerialize["chain_id"] = o.ChainId
	if !IsNil(o.RpcUrl) {
		toSerialize["rpc_url"] = o.RpcUrl
	}
	if !IsNil(o.WsUrl) {
		toSerialize["ws_url"] = o.WsUrl
	}
	if !IsNil(o.ExplorerUrl) {
		toSerialize["explorer_url"] = o.ExplorerUrl
	}
	if !IsNil(o.NativeCurrency) {
		toSerialize["native_currency"] = o.NativeCurrency
	}
	if !IsNil(o.IsTestnet) {
		toSerialize["is_testnet"] = o.IsTestnet
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	return toSerialize, nil
}

func (o *CreateChainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"display_name",
		"chain_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateChainRequest := _CreateChainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateChainRequest)

	if err != nil {
		return err
	}

	*o = CreateChainRequest(varCreateChainRequest)

	return err
}

type NullableCreateChainRequest struct {
	value *CreateChainRequest
	isSet bool
}

func (v NullableCreateChainRequest) Get() *CreateChainRequest {
	return v.value
}

func (v *NullableCreateChainRequest) Set(val *CreateChainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateChainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateChainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateChainRequest(val *CreateChainRequest) *NullableCreateChainRequest {
	return &NullableCreateChainRequest{value: val, isSet: true}
}

func (v NullableCreateChainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateChainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


