/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the UsageHistoryResponseEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageHistoryResponseEventsInner{}

// UsageHistoryResponseEventsInner struct for UsageHistoryResponseEventsInner
type UsageHistoryResponseEventsInner struct {
	Id *string `json:"id,omitempty"`
	PrincipalType *string `json:"principal_type,omitempty"`
	PrincipalId *string `json:"principal_id,omitempty"`
	Method *string `json:"method,omitempty"`
	Endpoint *string `json:"endpoint,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
	PriceUsd *string `json:"price_usd,omitempty"`
	IsPaid *bool `json:"is_paid,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewUsageHistoryResponseEventsInner instantiates a new UsageHistoryResponseEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageHistoryResponseEventsInner() *UsageHistoryResponseEventsInner {
	this := UsageHistoryResponseEventsInner{}
	return &this
}

// NewUsageHistoryResponseEventsInnerWithDefaults instantiates a new UsageHistoryResponseEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageHistoryResponseEventsInnerWithDefaults() *UsageHistoryResponseEventsInner {
	this := UsageHistoryResponseEventsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UsageHistoryResponseEventsInner) SetId(v string) {
	o.Id = &v
}

// GetPrincipalType returns the PrincipalType field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetPrincipalType() string {
	if o == nil || IsNil(o.PrincipalType) {
		var ret string
		return ret
	}
	return *o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetPrincipalTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PrincipalType) {
		return nil, false
	}
	return o.PrincipalType, true
}

// HasPrincipalType returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasPrincipalType() bool {
	if o != nil && !IsNil(o.PrincipalType) {
		return true
	}

	return false
}

// SetPrincipalType gets a reference to the given string and assigns it to the PrincipalType field.
func (o *UsageHistoryResponseEventsInner) SetPrincipalType(v string) {
	o.PrincipalType = &v
}

// GetPrincipalId returns the PrincipalId field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetPrincipalId() string {
	if o == nil || IsNil(o.PrincipalId) {
		var ret string
		return ret
	}
	return *o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetPrincipalIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrincipalId) {
		return nil, false
	}
	return o.PrincipalId, true
}

// HasPrincipalId returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasPrincipalId() bool {
	if o != nil && !IsNil(o.PrincipalId) {
		return true
	}

	return false
}

// SetPrincipalId gets a reference to the given string and assigns it to the PrincipalId field.
func (o *UsageHistoryResponseEventsInner) SetPrincipalId(v string) {
	o.PrincipalId = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *UsageHistoryResponseEventsInner) SetMethod(v string) {
	o.Method = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *UsageHistoryResponseEventsInner) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *UsageHistoryResponseEventsInner) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetPriceUsd returns the PriceUsd field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetPriceUsd() string {
	if o == nil || IsNil(o.PriceUsd) {
		var ret string
		return ret
	}
	return *o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetPriceUsdOk() (*string, bool) {
	if o == nil || IsNil(o.PriceUsd) {
		return nil, false
	}
	return o.PriceUsd, true
}

// HasPriceUsd returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasPriceUsd() bool {
	if o != nil && !IsNil(o.PriceUsd) {
		return true
	}

	return false
}

// SetPriceUsd gets a reference to the given string and assigns it to the PriceUsd field.
func (o *UsageHistoryResponseEventsInner) SetPriceUsd(v string) {
	o.PriceUsd = &v
}

// GetIsPaid returns the IsPaid field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetIsPaid() bool {
	if o == nil || IsNil(o.IsPaid) {
		var ret bool
		return ret
	}
	return *o.IsPaid
}

// GetIsPaidOk returns a tuple with the IsPaid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetIsPaidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPaid) {
		return nil, false
	}
	return o.IsPaid, true
}

// HasIsPaid returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasIsPaid() bool {
	if o != nil && !IsNil(o.IsPaid) {
		return true
	}

	return false
}

// SetIsPaid gets a reference to the given bool and assigns it to the IsPaid field.
func (o *UsageHistoryResponseEventsInner) SetIsPaid(v bool) {
	o.IsPaid = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UsageHistoryResponseEventsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageHistoryResponseEventsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UsageHistoryResponseEventsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UsageHistoryResponseEventsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o UsageHistoryResponseEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageHistoryResponseEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PrincipalType) {
		toSerialize["principal_type"] = o.PrincipalType
	}
	if !IsNil(o.PrincipalId) {
		toSerialize["principal_id"] = o.PrincipalId
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.PriceUsd) {
		toSerialize["price_usd"] = o.PriceUsd
	}
	if !IsNil(o.IsPaid) {
		toSerialize["is_paid"] = o.IsPaid
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableUsageHistoryResponseEventsInner struct {
	value *UsageHistoryResponseEventsInner
	isSet bool
}

func (v NullableUsageHistoryResponseEventsInner) Get() *UsageHistoryResponseEventsInner {
	return v.value
}

func (v *NullableUsageHistoryResponseEventsInner) Set(val *UsageHistoryResponseEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageHistoryResponseEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageHistoryResponseEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageHistoryResponseEventsInner(val *UsageHistoryResponseEventsInner) *NullableUsageHistoryResponseEventsInner {
	return &NullableUsageHistoryResponseEventsInner{value: val, isSet: true}
}

func (v NullableUsageHistoryResponseEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageHistoryResponseEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


