/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTreasuryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTreasuryRequest{}

// CreateTreasuryRequest struct for CreateTreasuryRequest
type CreateTreasuryRequest struct {
	// Display name (1–128 characters)
	Name string `json:"name"`
	// Deployed Safe contract address (0x-prefixed, 42 characters)
	SafeAddress string `json:"safe_address"`
	// Chain name (default base)
	Chain *string `json:"chain,omitempty"`
	// EVM chain ID (default 8453 for Base)
	ChainId *int32 `json:"chain_id,omitempty"`
	// Safe threshold (default 1)
	Threshold *int32 `json:"threshold,omitempty"`
	Signers []CreateTreasurySignerEntry `json:"signers,omitempty"`
}

type _CreateTreasuryRequest CreateTreasuryRequest

// NewCreateTreasuryRequest instantiates a new CreateTreasuryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTreasuryRequest(name string, safeAddress string) *CreateTreasuryRequest {
	this := CreateTreasuryRequest{}
	this.Name = name
	this.SafeAddress = safeAddress
	return &this
}

// NewCreateTreasuryRequestWithDefaults instantiates a new CreateTreasuryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTreasuryRequestWithDefaults() *CreateTreasuryRequest {
	this := CreateTreasuryRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTreasuryRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTreasuryRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTreasuryRequest) SetName(v string) {
	o.Name = v
}

// GetSafeAddress returns the SafeAddress field value
func (o *CreateTreasuryRequest) GetSafeAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SafeAddress
}

// GetSafeAddressOk returns a tuple with the SafeAddress field value
// and a boolean to check if the value has been set.
func (o *CreateTreasuryRequest) GetSafeAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SafeAddress, true
}

// SetSafeAddress sets field value
func (o *CreateTreasuryRequest) SetSafeAddress(v string) {
	o.SafeAddress = v
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *CreateTreasuryRequest) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTreasuryRequest) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *CreateTreasuryRequest) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *CreateTreasuryRequest) SetChain(v string) {
	o.Chain = &v
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *CreateTreasuryRequest) GetChainId() int32 {
	if o == nil || IsNil(o.ChainId) {
		var ret int32
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTreasuryRequest) GetChainIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *CreateTreasuryRequest) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given int32 and assigns it to the ChainId field.
func (o *CreateTreasuryRequest) SetChainId(v int32) {
	o.ChainId = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *CreateTreasuryRequest) GetThreshold() int32 {
	if o == nil || IsNil(o.Threshold) {
		var ret int32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTreasuryRequest) GetThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *CreateTreasuryRequest) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int32 and assigns it to the Threshold field.
func (o *CreateTreasuryRequest) SetThreshold(v int32) {
	o.Threshold = &v
}

// GetSigners returns the Signers field value if set, zero value otherwise.
func (o *CreateTreasuryRequest) GetSigners() []CreateTreasurySignerEntry {
	if o == nil || IsNil(o.Signers) {
		var ret []CreateTreasurySignerEntry
		return ret
	}
	return o.Signers
}

// GetSignersOk returns a tuple with the Signers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTreasuryRequest) GetSignersOk() ([]CreateTreasurySignerEntry, bool) {
	if o == nil || IsNil(o.Signers) {
		return nil, false
	}
	return o.Signers, true
}

// HasSigners returns a boolean if a field has been set.
func (o *CreateTreasuryRequest) HasSigners() bool {
	if o != nil && !IsNil(o.Signers) {
		return true
	}

	return false
}

// SetSigners gets a reference to the given []CreateTreasurySignerEntry and assigns it to the Signers field.
func (o *CreateTreasuryRequest) SetSigners(v []CreateTreasurySignerEntry) {
	o.Signers = v
}

func (o CreateTreasuryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTreasuryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["safe_address"] = o.SafeAddress
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.ChainId) {
		toSerialize["chain_id"] = o.ChainId
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.Signers) {
		toSerialize["signers"] = o.Signers
	}
	return toSerialize, nil
}

func (o *CreateTreasuryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"safe_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTreasuryRequest := _CreateTreasuryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTreasuryRequest)

	if err != nil {
		return err
	}

	*o = CreateTreasuryRequest(varCreateTreasuryRequest)

	return err
}

type NullableCreateTreasuryRequest struct {
	value *CreateTreasuryRequest
	isSet bool
}

func (v NullableCreateTreasuryRequest) Get() *CreateTreasuryRequest {
	return v.value
}

func (v *NullableCreateTreasuryRequest) Set(val *CreateTreasuryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTreasuryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTreasuryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTreasuryRequest(val *CreateTreasuryRequest) *NullableCreateTreasuryRequest {
	return &NullableCreateTreasuryRequest{value: val, isSet: true}
}

func (v NullableCreateTreasuryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTreasuryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


