/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ChainListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChainListResponse{}

// ChainListResponse struct for ChainListResponse
type ChainListResponse struct {
	Chains []ChainResponse `json:"chains,omitempty"`
}

// NewChainListResponse instantiates a new ChainListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChainListResponse() *ChainListResponse {
	this := ChainListResponse{}
	return &this
}

// NewChainListResponseWithDefaults instantiates a new ChainListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChainListResponseWithDefaults() *ChainListResponse {
	this := ChainListResponse{}
	return &this
}

// GetChains returns the Chains field value if set, zero value otherwise.
func (o *ChainListResponse) GetChains() []ChainResponse {
	if o == nil || IsNil(o.Chains) {
		var ret []ChainResponse
		return ret
	}
	return o.Chains
}

// GetChainsOk returns a tuple with the Chains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChainListResponse) GetChainsOk() ([]ChainResponse, bool) {
	if o == nil || IsNil(o.Chains) {
		return nil, false
	}
	return o.Chains, true
}

// HasChains returns a boolean if a field has been set.
func (o *ChainListResponse) HasChains() bool {
	if o != nil && !IsNil(o.Chains) {
		return true
	}

	return false
}

// SetChains gets a reference to the given []ChainResponse and assigns it to the Chains field.
func (o *ChainListResponse) SetChains(v []ChainResponse) {
	o.Chains = v
}

func (o ChainListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChainListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chains) {
		toSerialize["chains"] = o.Chains
	}
	return toSerialize, nil
}

type NullableChainListResponse struct {
	value *ChainListResponse
	isSet bool
}

func (v NullableChainListResponse) Get() *ChainListResponse {
	return v.value
}

func (v *NullableChainListResponse) Set(val *ChainListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChainListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChainListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChainListResponse(val *ChainListResponse) *NullableChainListResponse {
	return &NullableChainListResponse{value: val, isSet: true}
}

func (v NullableChainListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChainListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


