/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateTreasuryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTreasuryRequest{}

// UpdateTreasuryRequest struct for UpdateTreasuryRequest
type UpdateTreasuryRequest struct {
	Name *string `json:"name,omitempty"`
	Threshold *int32 `json:"threshold,omitempty"`
}

// NewUpdateTreasuryRequest instantiates a new UpdateTreasuryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTreasuryRequest() *UpdateTreasuryRequest {
	this := UpdateTreasuryRequest{}
	return &this
}

// NewUpdateTreasuryRequestWithDefaults instantiates a new UpdateTreasuryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTreasuryRequestWithDefaults() *UpdateTreasuryRequest {
	this := UpdateTreasuryRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateTreasuryRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTreasuryRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateTreasuryRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateTreasuryRequest) SetName(v string) {
	o.Name = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *UpdateTreasuryRequest) GetThreshold() int32 {
	if o == nil || IsNil(o.Threshold) {
		var ret int32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTreasuryRequest) GetThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *UpdateTreasuryRequest) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int32 and assigns it to the Threshold field.
func (o *UpdateTreasuryRequest) SetThreshold(v int32) {
	o.Threshold = &v
}

func (o UpdateTreasuryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTreasuryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	return toSerialize, nil
}

type NullableUpdateTreasuryRequest struct {
	value *UpdateTreasuryRequest
	isSet bool
}

func (v NullableUpdateTreasuryRequest) Get() *UpdateTreasuryRequest {
	return v.value
}

func (v *NullableUpdateTreasuryRequest) Set(val *UpdateTreasuryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTreasuryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTreasuryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTreasuryRequest(val *UpdateTreasuryRequest) *NullableUpdateTreasuryRequest {
	return &NullableUpdateTreasuryRequest{value: val, isSet: true}
}

func (v NullableUpdateTreasuryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTreasuryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


