/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateVaultRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVaultRequest{}

// CreateVaultRequest struct for CreateVaultRequest
type CreateVaultRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
}

type _CreateVaultRequest CreateVaultRequest

// NewCreateVaultRequest instantiates a new CreateVaultRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVaultRequest(name string) *CreateVaultRequest {
	this := CreateVaultRequest{}
	this.Name = name
	return &this
}

// NewCreateVaultRequestWithDefaults instantiates a new CreateVaultRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVaultRequestWithDefaults() *CreateVaultRequest {
	this := CreateVaultRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateVaultRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateVaultRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateVaultRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateVaultRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVaultRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateVaultRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateVaultRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CreateVaultRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVaultRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CreateVaultRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateVaultRequest := _CreateVaultRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateVaultRequest)

	if err != nil {
		return err
	}

	*o = CreateVaultRequest(varCreateVaultRequest)

	return err
}

type NullableCreateVaultRequest struct {
	value *CreateVaultRequest
	isSet bool
}

func (v NullableCreateVaultRequest) Get() *CreateVaultRequest {
	return v.value
}

func (v *NullableCreateVaultRequest) Set(val *CreateVaultRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVaultRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVaultRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVaultRequest(val *CreateVaultRequest) *NullableCreateVaultRequest {
	return &NullableCreateVaultRequest{value: val, isSet: true}
}

func (v NullableCreateVaultRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVaultRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


