/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SimulateBundleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimulateBundleRequest{}

// SimulateBundleRequest struct for SimulateBundleRequest
type SimulateBundleRequest struct {
	Transactions []SimulateTransactionRequest `json:"transactions"`
}

type _SimulateBundleRequest SimulateBundleRequest

// NewSimulateBundleRequest instantiates a new SimulateBundleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimulateBundleRequest(transactions []SimulateTransactionRequest) *SimulateBundleRequest {
	this := SimulateBundleRequest{}
	this.Transactions = transactions
	return &this
}

// NewSimulateBundleRequestWithDefaults instantiates a new SimulateBundleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimulateBundleRequestWithDefaults() *SimulateBundleRequest {
	this := SimulateBundleRequest{}
	return &this
}

// GetTransactions returns the Transactions field value
func (o *SimulateBundleRequest) GetTransactions() []SimulateTransactionRequest {
	if o == nil {
		var ret []SimulateTransactionRequest
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *SimulateBundleRequest) GetTransactionsOk() ([]SimulateTransactionRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *SimulateBundleRequest) SetTransactions(v []SimulateTransactionRequest) {
	o.Transactions = v
}

func (o SimulateBundleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimulateBundleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactions"] = o.Transactions
	return toSerialize, nil
}

func (o *SimulateBundleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSimulateBundleRequest := _SimulateBundleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSimulateBundleRequest)

	if err != nil {
		return err
	}

	*o = SimulateBundleRequest(varSimulateBundleRequest)

	return err
}

type NullableSimulateBundleRequest struct {
	value *SimulateBundleRequest
	isSet bool
}

func (v NullableSimulateBundleRequest) Get() *SimulateBundleRequest {
	return v.value
}

func (v *NullableSimulateBundleRequest) Set(val *SimulateBundleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSimulateBundleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSimulateBundleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimulateBundleRequest(val *SimulateBundleRequest) *NullableSimulateBundleRequest {
	return &NullableSimulateBundleRequest{value: val, isSet: true}
}

func (v NullableSimulateBundleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimulateBundleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


