/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the UserProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfileResponse{}

// UserProfileResponse struct for UserProfileResponse
type UserProfileResponse struct {
	Id *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	AuthMethod *string `json:"auth_method,omitempty"`
	Role *string `json:"role,omitempty"`
	EmailVerified *bool `json:"email_verified,omitempty"`
	MarketingEmails *bool `json:"marketing_emails,omitempty"`
	TotpEnabled *bool `json:"totp_enabled,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewUserProfileResponse instantiates a new UserProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfileResponse() *UserProfileResponse {
	this := UserProfileResponse{}
	return &this
}

// NewUserProfileResponseWithDefaults instantiates a new UserProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfileResponseWithDefaults() *UserProfileResponse {
	this := UserProfileResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserProfileResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserProfileResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserProfileResponse) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserProfileResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserProfileResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserProfileResponse) SetEmail(v string) {
	o.Email = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *UserProfileResponse) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UserProfileResponse) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *UserProfileResponse) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetAuthMethod returns the AuthMethod field value if set, zero value otherwise.
func (o *UserProfileResponse) GetAuthMethod() string {
	if o == nil || IsNil(o.AuthMethod) {
		var ret string
		return ret
	}
	return *o.AuthMethod
}

// GetAuthMethodOk returns a tuple with the AuthMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetAuthMethodOk() (*string, bool) {
	if o == nil || IsNil(o.AuthMethod) {
		return nil, false
	}
	return o.AuthMethod, true
}

// HasAuthMethod returns a boolean if a field has been set.
func (o *UserProfileResponse) HasAuthMethod() bool {
	if o != nil && !IsNil(o.AuthMethod) {
		return true
	}

	return false
}

// SetAuthMethod gets a reference to the given string and assigns it to the AuthMethod field.
func (o *UserProfileResponse) SetAuthMethod(v string) {
	o.AuthMethod = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UserProfileResponse) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UserProfileResponse) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UserProfileResponse) SetRole(v string) {
	o.Role = &v
}

// GetEmailVerified returns the EmailVerified field value if set, zero value otherwise.
func (o *UserProfileResponse) GetEmailVerified() bool {
	if o == nil || IsNil(o.EmailVerified) {
		var ret bool
		return ret
	}
	return *o.EmailVerified
}

// GetEmailVerifiedOk returns a tuple with the EmailVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetEmailVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailVerified) {
		return nil, false
	}
	return o.EmailVerified, true
}

// HasEmailVerified returns a boolean if a field has been set.
func (o *UserProfileResponse) HasEmailVerified() bool {
	if o != nil && !IsNil(o.EmailVerified) {
		return true
	}

	return false
}

// SetEmailVerified gets a reference to the given bool and assigns it to the EmailVerified field.
func (o *UserProfileResponse) SetEmailVerified(v bool) {
	o.EmailVerified = &v
}

// GetMarketingEmails returns the MarketingEmails field value if set, zero value otherwise.
func (o *UserProfileResponse) GetMarketingEmails() bool {
	if o == nil || IsNil(o.MarketingEmails) {
		var ret bool
		return ret
	}
	return *o.MarketingEmails
}

// GetMarketingEmailsOk returns a tuple with the MarketingEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetMarketingEmailsOk() (*bool, bool) {
	if o == nil || IsNil(o.MarketingEmails) {
		return nil, false
	}
	return o.MarketingEmails, true
}

// HasMarketingEmails returns a boolean if a field has been set.
func (o *UserProfileResponse) HasMarketingEmails() bool {
	if o != nil && !IsNil(o.MarketingEmails) {
		return true
	}

	return false
}

// SetMarketingEmails gets a reference to the given bool and assigns it to the MarketingEmails field.
func (o *UserProfileResponse) SetMarketingEmails(v bool) {
	o.MarketingEmails = &v
}

// GetTotpEnabled returns the TotpEnabled field value if set, zero value otherwise.
func (o *UserProfileResponse) GetTotpEnabled() bool {
	if o == nil || IsNil(o.TotpEnabled) {
		var ret bool
		return ret
	}
	return *o.TotpEnabled
}

// GetTotpEnabledOk returns a tuple with the TotpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetTotpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TotpEnabled) {
		return nil, false
	}
	return o.TotpEnabled, true
}

// HasTotpEnabled returns a boolean if a field has been set.
func (o *UserProfileResponse) HasTotpEnabled() bool {
	if o != nil && !IsNil(o.TotpEnabled) {
		return true
	}

	return false
}

// SetTotpEnabled gets a reference to the given bool and assigns it to the TotpEnabled field.
func (o *UserProfileResponse) SetTotpEnabled(v bool) {
	o.TotpEnabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UserProfileResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UserProfileResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UserProfileResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o UserProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.AuthMethod) {
		toSerialize["auth_method"] = o.AuthMethod
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.EmailVerified) {
		toSerialize["email_verified"] = o.EmailVerified
	}
	if !IsNil(o.MarketingEmails) {
		toSerialize["marketing_emails"] = o.MarketingEmails
	}
	if !IsNil(o.TotpEnabled) {
		toSerialize["totp_enabled"] = o.TotpEnabled
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableUserProfileResponse struct {
	value *UserProfileResponse
	isSet bool
}

func (v NullableUserProfileResponse) Get() *UserProfileResponse {
	return v.value
}

func (v *NullableUserProfileResponse) Set(val *UserProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfileResponse(val *UserProfileResponse) *NullableUserProfileResponse {
	return &NullableUserProfileResponse{value: val, isSet: true}
}

func (v NullableUserProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


