/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AccessRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessRequestResponse{}

// AccessRequestResponse struct for AccessRequestResponse
type AccessRequestResponse struct {
	Id *string `json:"id,omitempty"`
	TreasuryId *string `json:"treasury_id,omitempty"`
	AgentId *string `json:"agent_id,omitempty"`
	Status *string `json:"status,omitempty"`
	Reason *string `json:"reason,omitempty"`
	RequestedAt *time.Time `json:"requested_at,omitempty"`
	ResolvedBy *string `json:"resolved_by,omitempty"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
}

// NewAccessRequestResponse instantiates a new AccessRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessRequestResponse() *AccessRequestResponse {
	this := AccessRequestResponse{}
	return &this
}

// NewAccessRequestResponseWithDefaults instantiates a new AccessRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessRequestResponseWithDefaults() *AccessRequestResponse {
	this := AccessRequestResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AccessRequestResponse) SetId(v string) {
	o.Id = &v
}

// GetTreasuryId returns the TreasuryId field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetTreasuryId() string {
	if o == nil || IsNil(o.TreasuryId) {
		var ret string
		return ret
	}
	return *o.TreasuryId
}

// GetTreasuryIdOk returns a tuple with the TreasuryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetTreasuryIdOk() (*string, bool) {
	if o == nil || IsNil(o.TreasuryId) {
		return nil, false
	}
	return o.TreasuryId, true
}

// HasTreasuryId returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasTreasuryId() bool {
	if o != nil && !IsNil(o.TreasuryId) {
		return true
	}

	return false
}

// SetTreasuryId gets a reference to the given string and assigns it to the TreasuryId field.
func (o *AccessRequestResponse) SetTreasuryId(v string) {
	o.TreasuryId = &v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *AccessRequestResponse) SetAgentId(v string) {
	o.AgentId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AccessRequestResponse) SetStatus(v string) {
	o.Status = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AccessRequestResponse) SetReason(v string) {
	o.Reason = &v
}

// GetRequestedAt returns the RequestedAt field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetRequestedAt() time.Time {
	if o == nil || IsNil(o.RequestedAt) {
		var ret time.Time
		return ret
	}
	return *o.RequestedAt
}

// GetRequestedAtOk returns a tuple with the RequestedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetRequestedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RequestedAt) {
		return nil, false
	}
	return o.RequestedAt, true
}

// HasRequestedAt returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasRequestedAt() bool {
	if o != nil && !IsNil(o.RequestedAt) {
		return true
	}

	return false
}

// SetRequestedAt gets a reference to the given time.Time and assigns it to the RequestedAt field.
func (o *AccessRequestResponse) SetRequestedAt(v time.Time) {
	o.RequestedAt = &v
}

// GetResolvedBy returns the ResolvedBy field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetResolvedBy() string {
	if o == nil || IsNil(o.ResolvedBy) {
		var ret string
		return ret
	}
	return *o.ResolvedBy
}

// GetResolvedByOk returns a tuple with the ResolvedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetResolvedByOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedBy) {
		return nil, false
	}
	return o.ResolvedBy, true
}

// HasResolvedBy returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasResolvedBy() bool {
	if o != nil && !IsNil(o.ResolvedBy) {
		return true
	}

	return false
}

// SetResolvedBy gets a reference to the given string and assigns it to the ResolvedBy field.
func (o *AccessRequestResponse) SetResolvedBy(v string) {
	o.ResolvedBy = &v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise.
func (o *AccessRequestResponse) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessRequestResponse) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolvedAt) {
		return nil, false
	}
	return o.ResolvedAt, true
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *AccessRequestResponse) HasResolvedAt() bool {
	if o != nil && !IsNil(o.ResolvedAt) {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given time.Time and assigns it to the ResolvedAt field.
func (o *AccessRequestResponse) SetResolvedAt(v time.Time) {
	o.ResolvedAt = &v
}

func (o AccessRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TreasuryId) {
		toSerialize["treasury_id"] = o.TreasuryId
	}
	if !IsNil(o.AgentId) {
		toSerialize["agent_id"] = o.AgentId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.RequestedAt) {
		toSerialize["requested_at"] = o.RequestedAt
	}
	if !IsNil(o.ResolvedBy) {
		toSerialize["resolved_by"] = o.ResolvedBy
	}
	if !IsNil(o.ResolvedAt) {
		toSerialize["resolved_at"] = o.ResolvedAt
	}
	return toSerialize, nil
}

type NullableAccessRequestResponse struct {
	value *AccessRequestResponse
	isSet bool
}

func (v NullableAccessRequestResponse) Get() *AccessRequestResponse {
	return v.value
}

func (v *NullableAccessRequestResponse) Set(val *AccessRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessRequestResponse(val *AccessRequestResponse) *NullableAccessRequestResponse {
	return &NullableAccessRequestResponse{value: val, isSet: true}
}

func (v NullableAccessRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


