/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdminUsersListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUsersListResponse{}

// AdminUsersListResponse struct for AdminUsersListResponse
type AdminUsersListResponse struct {
	Users []AdminUsersListResponseUsersInner `json:"users,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewAdminUsersListResponse instantiates a new AdminUsersListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUsersListResponse() *AdminUsersListResponse {
	this := AdminUsersListResponse{}
	return &this
}

// NewAdminUsersListResponseWithDefaults instantiates a new AdminUsersListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUsersListResponseWithDefaults() *AdminUsersListResponse {
	this := AdminUsersListResponse{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *AdminUsersListResponse) GetUsers() []AdminUsersListResponseUsersInner {
	if o == nil || IsNil(o.Users) {
		var ret []AdminUsersListResponseUsersInner
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUsersListResponse) GetUsersOk() ([]AdminUsersListResponseUsersInner, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *AdminUsersListResponse) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []AdminUsersListResponseUsersInner and assigns it to the Users field.
func (o *AdminUsersListResponse) SetUsers(v []AdminUsersListResponseUsersInner) {
	o.Users = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AdminUsersListResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminUsersListResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AdminUsersListResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AdminUsersListResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o AdminUsersListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUsersListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableAdminUsersListResponse struct {
	value *AdminUsersListResponse
	isSet bool
}

func (v NullableAdminUsersListResponse) Get() *AdminUsersListResponse {
	return v.value
}

func (v *NullableAdminUsersListResponse) Set(val *AdminUsersListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUsersListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUsersListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUsersListResponse(val *AdminUsersListResponse) *NullableAdminUsersListResponse {
	return &NullableAdminUsersListResponse{value: val, isSet: true}
}

func (v NullableAdminUsersListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUsersListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


