/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CheckoutUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutUrlResponse{}

// CheckoutUrlResponse struct for CheckoutUrlResponse
type CheckoutUrlResponse struct {
	CheckoutUrl *string `json:"checkout_url,omitempty"`
}

// NewCheckoutUrlResponse instantiates a new CheckoutUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutUrlResponse() *CheckoutUrlResponse {
	this := CheckoutUrlResponse{}
	return &this
}

// NewCheckoutUrlResponseWithDefaults instantiates a new CheckoutUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutUrlResponseWithDefaults() *CheckoutUrlResponse {
	this := CheckoutUrlResponse{}
	return &this
}

// GetCheckoutUrl returns the CheckoutUrl field value if set, zero value otherwise.
func (o *CheckoutUrlResponse) GetCheckoutUrl() string {
	if o == nil || IsNil(o.CheckoutUrl) {
		var ret string
		return ret
	}
	return *o.CheckoutUrl
}

// GetCheckoutUrlOk returns a tuple with the CheckoutUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutUrlResponse) GetCheckoutUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CheckoutUrl) {
		return nil, false
	}
	return o.CheckoutUrl, true
}

// HasCheckoutUrl returns a boolean if a field has been set.
func (o *CheckoutUrlResponse) HasCheckoutUrl() bool {
	if o != nil && !IsNil(o.CheckoutUrl) {
		return true
	}

	return false
}

// SetCheckoutUrl gets a reference to the given string and assigns it to the CheckoutUrl field.
func (o *CheckoutUrlResponse) SetCheckoutUrl(v string) {
	o.CheckoutUrl = &v
}

func (o CheckoutUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckoutUrl) {
		toSerialize["checkout_url"] = o.CheckoutUrl
	}
	return toSerialize, nil
}

type NullableCheckoutUrlResponse struct {
	value *CheckoutUrlResponse
	isSet bool
}

func (v NullableCheckoutUrlResponse) Get() *CheckoutUrlResponse {
	return v.value
}

func (v *NullableCheckoutUrlResponse) Set(val *CheckoutUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutUrlResponse(val *CheckoutUrlResponse) *NullableCheckoutUrlResponse {
	return &NullableCheckoutUrlResponse{value: val, isSet: true}
}

func (v NullableCheckoutUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


