/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceApproveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceApproveRequest{}

// DeviceApproveRequest struct for DeviceApproveRequest
type DeviceApproveRequest struct {
	UserCode string `json:"user_code"`
}

type _DeviceApproveRequest DeviceApproveRequest

// NewDeviceApproveRequest instantiates a new DeviceApproveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceApproveRequest(userCode string) *DeviceApproveRequest {
	this := DeviceApproveRequest{}
	this.UserCode = userCode
	return &this
}

// NewDeviceApproveRequestWithDefaults instantiates a new DeviceApproveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceApproveRequestWithDefaults() *DeviceApproveRequest {
	this := DeviceApproveRequest{}
	return &this
}

// GetUserCode returns the UserCode field value
func (o *DeviceApproveRequest) GetUserCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserCode
}

// GetUserCodeOk returns a tuple with the UserCode field value
// and a boolean to check if the value has been set.
func (o *DeviceApproveRequest) GetUserCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserCode, true
}

// SetUserCode sets field value
func (o *DeviceApproveRequest) SetUserCode(v string) {
	o.UserCode = v
}

func (o DeviceApproveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceApproveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_code"] = o.UserCode
	return toSerialize, nil
}

func (o *DeviceApproveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceApproveRequest := _DeviceApproveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceApproveRequest)

	if err != nil {
		return err
	}

	*o = DeviceApproveRequest(varDeviceApproveRequest)

	return err
}

type NullableDeviceApproveRequest struct {
	value *DeviceApproveRequest
	isSet bool
}

func (v NullableDeviceApproveRequest) Get() *DeviceApproveRequest {
	return v.value
}

func (v *NullableDeviceApproveRequest) Set(val *DeviceApproveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceApproveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceApproveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceApproveRequest(val *DeviceApproveRequest) *NullableDeviceApproveRequest {
	return &NullableDeviceApproveRequest{value: val, isSet: true}
}

func (v NullableDeviceApproveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceApproveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


