/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyResponse{}

// PolicyResponse struct for PolicyResponse
type PolicyResponse struct {
	Id string `json:"id"`
	VaultId string `json:"vault_id"`
	SecretPathPattern string `json:"secret_path_pattern"`
	PrincipalType string `json:"principal_type"`
	PrincipalId string `json:"principal_id"`
	Permissions []string `json:"permissions"`
	Conditions map[string]interface{} `json:"conditions,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedByType *string `json:"created_by_type,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

type _PolicyResponse PolicyResponse

// NewPolicyResponse instantiates a new PolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyResponse(id string, vaultId string, secretPathPattern string, principalType string, principalId string, permissions []string, createdAt time.Time) *PolicyResponse {
	this := PolicyResponse{}
	this.Id = id
	this.VaultId = vaultId
	this.SecretPathPattern = secretPathPattern
	this.PrincipalType = principalType
	this.PrincipalId = principalId
	this.Permissions = permissions
	this.CreatedAt = createdAt
	return &this
}

// NewPolicyResponseWithDefaults instantiates a new PolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyResponseWithDefaults() *PolicyResponse {
	this := PolicyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *PolicyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PolicyResponse) SetId(v string) {
	o.Id = v
}

// GetVaultId returns the VaultId field value
func (o *PolicyResponse) GetVaultId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VaultId
}

// GetVaultIdOk returns a tuple with the VaultId field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetVaultIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VaultId, true
}

// SetVaultId sets field value
func (o *PolicyResponse) SetVaultId(v string) {
	o.VaultId = v
}

// GetSecretPathPattern returns the SecretPathPattern field value
func (o *PolicyResponse) GetSecretPathPattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretPathPattern
}

// GetSecretPathPatternOk returns a tuple with the SecretPathPattern field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetSecretPathPatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretPathPattern, true
}

// SetSecretPathPattern sets field value
func (o *PolicyResponse) SetSecretPathPattern(v string) {
	o.SecretPathPattern = v
}

// GetPrincipalType returns the PrincipalType field value
func (o *PolicyResponse) GetPrincipalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetPrincipalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalType, true
}

// SetPrincipalType sets field value
func (o *PolicyResponse) SetPrincipalType(v string) {
	o.PrincipalType = v
}

// GetPrincipalId returns the PrincipalId field value
func (o *PolicyResponse) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *PolicyResponse) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetPermissions returns the Permissions field value
func (o *PolicyResponse) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetPermissionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Permissions, true
}

// SetPermissions sets field value
func (o *PolicyResponse) SetPermissions(v []string) {
	o.Permissions = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *PolicyResponse) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *PolicyResponse) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *PolicyResponse) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *PolicyResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *PolicyResponse) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *PolicyResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *PolicyResponse) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *PolicyResponse) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *PolicyResponse) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreatedByType returns the CreatedByType field value if set, zero value otherwise.
func (o *PolicyResponse) GetCreatedByType() string {
	if o == nil || IsNil(o.CreatedByType) {
		var ret string
		return ret
	}
	return *o.CreatedByType
}

// GetCreatedByTypeOk returns a tuple with the CreatedByType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetCreatedByTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByType) {
		return nil, false
	}
	return o.CreatedByType, true
}

// HasCreatedByType returns a boolean if a field has been set.
func (o *PolicyResponse) HasCreatedByType() bool {
	if o != nil && !IsNil(o.CreatedByType) {
		return true
	}

	return false
}

// SetCreatedByType gets a reference to the given string and assigns it to the CreatedByType field.
func (o *PolicyResponse) SetCreatedByType(v string) {
	o.CreatedByType = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PolicyResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PolicyResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PolicyResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o PolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["vault_id"] = o.VaultId
	toSerialize["secret_path_pattern"] = o.SecretPathPattern
	toSerialize["principal_type"] = o.PrincipalType
	toSerialize["principal_id"] = o.PrincipalId
	toSerialize["permissions"] = o.Permissions
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.CreatedByType) {
		toSerialize["created_by_type"] = o.CreatedByType
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *PolicyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"vault_id",
		"secret_path_pattern",
		"principal_type",
		"principal_id",
		"permissions",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyResponse := _PolicyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyResponse)

	if err != nil {
		return err
	}

	*o = PolicyResponse(varPolicyResponse)

	return err
}

type NullablePolicyResponse struct {
	value *PolicyResponse
	isSet bool
}

func (v NullablePolicyResponse) Get() *PolicyResponse {
	return v.value
}

func (v *NullablePolicyResponse) Set(val *PolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyResponse(val *PolicyResponse) *NullablePolicyResponse {
	return &NullablePolicyResponse{value: val, isSet: true}
}

func (v NullablePolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


