/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubmitTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitTransactionRequest{}

// SubmitTransactionRequest struct for SubmitTransactionRequest
type SubmitTransactionRequest struct {
	// Destination address (0x-prefixed)
	To string `json:"to"`
	// Value in ETH
	Value string `json:"value"`
	// Chain name or numeric ID
	Chain string `json:"chain"`
	// Hex-encoded calldata
	Data *string `json:"data,omitempty"`
	SigningKeyPath *string `json:"signing_key_path,omitempty"`
	Nonce *int32 `json:"nonce,omitempty"`
	GasPrice *string `json:"gas_price,omitempty"`
	GasLimit *int32 `json:"gas_limit,omitempty"`
	MaxFeePerGas *string `json:"max_fee_per_gas,omitempty"`
	MaxPriorityFeePerGas *string `json:"max_priority_fee_per_gas,omitempty"`
	SimulateFirst *bool `json:"simulate_first,omitempty"`
}

type _SubmitTransactionRequest SubmitTransactionRequest

// NewSubmitTransactionRequest instantiates a new SubmitTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitTransactionRequest(to string, value string, chain string) *SubmitTransactionRequest {
	this := SubmitTransactionRequest{}
	this.To = to
	this.Value = value
	this.Chain = chain
	var simulateFirst bool = false
	this.SimulateFirst = &simulateFirst
	return &this
}

// NewSubmitTransactionRequestWithDefaults instantiates a new SubmitTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitTransactionRequestWithDefaults() *SubmitTransactionRequest {
	this := SubmitTransactionRequest{}
	var simulateFirst bool = false
	this.SimulateFirst = &simulateFirst
	return &this
}

// GetTo returns the To field value
func (o *SubmitTransactionRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *SubmitTransactionRequest) SetTo(v string) {
	o.To = v
}

// GetValue returns the Value field value
func (o *SubmitTransactionRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SubmitTransactionRequest) SetValue(v string) {
	o.Value = v
}

// GetChain returns the Chain field value
func (o *SubmitTransactionRequest) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *SubmitTransactionRequest) SetChain(v string) {
	o.Chain = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *SubmitTransactionRequest) SetData(v string) {
	o.Data = &v
}

// GetSigningKeyPath returns the SigningKeyPath field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetSigningKeyPath() string {
	if o == nil || IsNil(o.SigningKeyPath) {
		var ret string
		return ret
	}
	return *o.SigningKeyPath
}

// GetSigningKeyPathOk returns a tuple with the SigningKeyPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetSigningKeyPathOk() (*string, bool) {
	if o == nil || IsNil(o.SigningKeyPath) {
		return nil, false
	}
	return o.SigningKeyPath, true
}

// HasSigningKeyPath returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasSigningKeyPath() bool {
	if o != nil && !IsNil(o.SigningKeyPath) {
		return true
	}

	return false
}

// SetSigningKeyPath gets a reference to the given string and assigns it to the SigningKeyPath field.
func (o *SubmitTransactionRequest) SetSigningKeyPath(v string) {
	o.SigningKeyPath = &v
}

// GetNonce returns the Nonce field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetNonce() int32 {
	if o == nil || IsNil(o.Nonce) {
		var ret int32
		return ret
	}
	return *o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetNonceOk() (*int32, bool) {
	if o == nil || IsNil(o.Nonce) {
		return nil, false
	}
	return o.Nonce, true
}

// HasNonce returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasNonce() bool {
	if o != nil && !IsNil(o.Nonce) {
		return true
	}

	return false
}

// SetNonce gets a reference to the given int32 and assigns it to the Nonce field.
func (o *SubmitTransactionRequest) SetNonce(v int32) {
	o.Nonce = &v
}

// GetGasPrice returns the GasPrice field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetGasPrice() string {
	if o == nil || IsNil(o.GasPrice) {
		var ret string
		return ret
	}
	return *o.GasPrice
}

// GetGasPriceOk returns a tuple with the GasPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetGasPriceOk() (*string, bool) {
	if o == nil || IsNil(o.GasPrice) {
		return nil, false
	}
	return o.GasPrice, true
}

// HasGasPrice returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasGasPrice() bool {
	if o != nil && !IsNil(o.GasPrice) {
		return true
	}

	return false
}

// SetGasPrice gets a reference to the given string and assigns it to the GasPrice field.
func (o *SubmitTransactionRequest) SetGasPrice(v string) {
	o.GasPrice = &v
}

// GetGasLimit returns the GasLimit field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetGasLimit() int32 {
	if o == nil || IsNil(o.GasLimit) {
		var ret int32
		return ret
	}
	return *o.GasLimit
}

// GetGasLimitOk returns a tuple with the GasLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetGasLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.GasLimit) {
		return nil, false
	}
	return o.GasLimit, true
}

// HasGasLimit returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasGasLimit() bool {
	if o != nil && !IsNil(o.GasLimit) {
		return true
	}

	return false
}

// SetGasLimit gets a reference to the given int32 and assigns it to the GasLimit field.
func (o *SubmitTransactionRequest) SetGasLimit(v int32) {
	o.GasLimit = &v
}

// GetMaxFeePerGas returns the MaxFeePerGas field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetMaxFeePerGas() string {
	if o == nil || IsNil(o.MaxFeePerGas) {
		var ret string
		return ret
	}
	return *o.MaxFeePerGas
}

// GetMaxFeePerGasOk returns a tuple with the MaxFeePerGas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetMaxFeePerGasOk() (*string, bool) {
	if o == nil || IsNil(o.MaxFeePerGas) {
		return nil, false
	}
	return o.MaxFeePerGas, true
}

// HasMaxFeePerGas returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasMaxFeePerGas() bool {
	if o != nil && !IsNil(o.MaxFeePerGas) {
		return true
	}

	return false
}

// SetMaxFeePerGas gets a reference to the given string and assigns it to the MaxFeePerGas field.
func (o *SubmitTransactionRequest) SetMaxFeePerGas(v string) {
	o.MaxFeePerGas = &v
}

// GetMaxPriorityFeePerGas returns the MaxPriorityFeePerGas field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetMaxPriorityFeePerGas() string {
	if o == nil || IsNil(o.MaxPriorityFeePerGas) {
		var ret string
		return ret
	}
	return *o.MaxPriorityFeePerGas
}

// GetMaxPriorityFeePerGasOk returns a tuple with the MaxPriorityFeePerGas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetMaxPriorityFeePerGasOk() (*string, bool) {
	if o == nil || IsNil(o.MaxPriorityFeePerGas) {
		return nil, false
	}
	return o.MaxPriorityFeePerGas, true
}

// HasMaxPriorityFeePerGas returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasMaxPriorityFeePerGas() bool {
	if o != nil && !IsNil(o.MaxPriorityFeePerGas) {
		return true
	}

	return false
}

// SetMaxPriorityFeePerGas gets a reference to the given string and assigns it to the MaxPriorityFeePerGas field.
func (o *SubmitTransactionRequest) SetMaxPriorityFeePerGas(v string) {
	o.MaxPriorityFeePerGas = &v
}

// GetSimulateFirst returns the SimulateFirst field value if set, zero value otherwise.
func (o *SubmitTransactionRequest) GetSimulateFirst() bool {
	if o == nil || IsNil(o.SimulateFirst) {
		var ret bool
		return ret
	}
	return *o.SimulateFirst
}

// GetSimulateFirstOk returns a tuple with the SimulateFirst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitTransactionRequest) GetSimulateFirstOk() (*bool, bool) {
	if o == nil || IsNil(o.SimulateFirst) {
		return nil, false
	}
	return o.SimulateFirst, true
}

// HasSimulateFirst returns a boolean if a field has been set.
func (o *SubmitTransactionRequest) HasSimulateFirst() bool {
	if o != nil && !IsNil(o.SimulateFirst) {
		return true
	}

	return false
}

// SetSimulateFirst gets a reference to the given bool and assigns it to the SimulateFirst field.
func (o *SubmitTransactionRequest) SetSimulateFirst(v bool) {
	o.SimulateFirst = &v
}

func (o SubmitTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["to"] = o.To
	toSerialize["value"] = o.Value
	toSerialize["chain"] = o.Chain
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.SigningKeyPath) {
		toSerialize["signing_key_path"] = o.SigningKeyPath
	}
	if !IsNil(o.Nonce) {
		toSerialize["nonce"] = o.Nonce
	}
	if !IsNil(o.GasPrice) {
		toSerialize["gas_price"] = o.GasPrice
	}
	if !IsNil(o.GasLimit) {
		toSerialize["gas_limit"] = o.GasLimit
	}
	if !IsNil(o.MaxFeePerGas) {
		toSerialize["max_fee_per_gas"] = o.MaxFeePerGas
	}
	if !IsNil(o.MaxPriorityFeePerGas) {
		toSerialize["max_priority_fee_per_gas"] = o.MaxPriorityFeePerGas
	}
	if !IsNil(o.SimulateFirst) {
		toSerialize["simulate_first"] = o.SimulateFirst
	}
	return toSerialize, nil
}

func (o *SubmitTransactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"to",
		"value",
		"chain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmitTransactionRequest := _SubmitTransactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmitTransactionRequest)

	if err != nil {
		return err
	}

	*o = SubmitTransactionRequest(varSubmitTransactionRequest)

	return err
}

type NullableSubmitTransactionRequest struct {
	value *SubmitTransactionRequest
	isSet bool
}

func (v NullableSubmitTransactionRequest) Get() *SubmitTransactionRequest {
	return v.value
}

func (v *NullableSubmitTransactionRequest) Set(val *SubmitTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitTransactionRequest(val *SubmitTransactionRequest) *NullableSubmitTransactionRequest {
	return &NullableSubmitTransactionRequest{value: val, isSet: true}
}

func (v NullableSubmitTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


