/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListTreasuryAccessRequests200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTreasuryAccessRequests200Response{}

// ListTreasuryAccessRequests200Response struct for ListTreasuryAccessRequests200Response
type ListTreasuryAccessRequests200Response struct {
	Requests []AccessRequestResponse `json:"requests,omitempty"`
}

// NewListTreasuryAccessRequests200Response instantiates a new ListTreasuryAccessRequests200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTreasuryAccessRequests200Response() *ListTreasuryAccessRequests200Response {
	this := ListTreasuryAccessRequests200Response{}
	return &this
}

// NewListTreasuryAccessRequests200ResponseWithDefaults instantiates a new ListTreasuryAccessRequests200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTreasuryAccessRequests200ResponseWithDefaults() *ListTreasuryAccessRequests200Response {
	this := ListTreasuryAccessRequests200Response{}
	return &this
}

// GetRequests returns the Requests field value if set, zero value otherwise.
func (o *ListTreasuryAccessRequests200Response) GetRequests() []AccessRequestResponse {
	if o == nil || IsNil(o.Requests) {
		var ret []AccessRequestResponse
		return ret
	}
	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTreasuryAccessRequests200Response) GetRequestsOk() ([]AccessRequestResponse, bool) {
	if o == nil || IsNil(o.Requests) {
		return nil, false
	}
	return o.Requests, true
}

// HasRequests returns a boolean if a field has been set.
func (o *ListTreasuryAccessRequests200Response) HasRequests() bool {
	if o != nil && !IsNil(o.Requests) {
		return true
	}

	return false
}

// SetRequests gets a reference to the given []AccessRequestResponse and assigns it to the Requests field.
func (o *ListTreasuryAccessRequests200Response) SetRequests(v []AccessRequestResponse) {
	o.Requests = v
}

func (o ListTreasuryAccessRequests200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTreasuryAccessRequests200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requests) {
		toSerialize["requests"] = o.Requests
	}
	return toSerialize, nil
}

type NullableListTreasuryAccessRequests200Response struct {
	value *ListTreasuryAccessRequests200Response
	isSet bool
}

func (v NullableListTreasuryAccessRequests200Response) Get() *ListTreasuryAccessRequests200Response {
	return v.value
}

func (v *NullableListTreasuryAccessRequests200Response) Set(val *ListTreasuryAccessRequests200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTreasuryAccessRequests200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTreasuryAccessRequests200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTreasuryAccessRequests200Response(val *ListTreasuryAccessRequests200Response) *NullableListTreasuryAccessRequests200Response {
	return &NullableListTreasuryAccessRequests200Response{value: val, isSet: true}
}

func (v NullableListTreasuryAccessRequests200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTreasuryAccessRequests200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


