/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteMeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteMeRequest{}

// DeleteMeRequest struct for DeleteMeRequest
type DeleteMeRequest struct {
	// Must be \"DELETE MY ACCOUNT\"
	Confirmation string `json:"confirmation"`
}

type _DeleteMeRequest DeleteMeRequest

// NewDeleteMeRequest instantiates a new DeleteMeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteMeRequest(confirmation string) *DeleteMeRequest {
	this := DeleteMeRequest{}
	this.Confirmation = confirmation
	return &this
}

// NewDeleteMeRequestWithDefaults instantiates a new DeleteMeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteMeRequestWithDefaults() *DeleteMeRequest {
	this := DeleteMeRequest{}
	return &this
}

// GetConfirmation returns the Confirmation field value
func (o *DeleteMeRequest) GetConfirmation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Confirmation
}

// GetConfirmationOk returns a tuple with the Confirmation field value
// and a boolean to check if the value has been set.
func (o *DeleteMeRequest) GetConfirmationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confirmation, true
}

// SetConfirmation sets field value
func (o *DeleteMeRequest) SetConfirmation(v string) {
	o.Confirmation = v
}

func (o DeleteMeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteMeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["confirmation"] = o.Confirmation
	return toSerialize, nil
}

func (o *DeleteMeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"confirmation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteMeRequest := _DeleteMeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteMeRequest)

	if err != nil {
		return err
	}

	*o = DeleteMeRequest(varDeleteMeRequest)

	return err
}

type NullableDeleteMeRequest struct {
	value *DeleteMeRequest
	isSet bool
}

func (v NullableDeleteMeRequest) Get() *DeleteMeRequest {
	return v.value
}

func (v *NullableDeleteMeRequest) Set(val *DeleteMeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteMeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteMeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteMeRequest(val *DeleteMeRequest) *NullableDeleteMeRequest {
	return &NullableDeleteMeRequest{value: val, isSet: true}
}

func (v NullableDeleteMeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteMeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


