/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.4.1
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiKeyCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyCreatedResponse{}

// ApiKeyCreatedResponse struct for ApiKeyCreatedResponse
type ApiKeyCreatedResponse struct {
	Key *ApiKeyResponse `json:"key,omitempty"`
	// Full key (shown once)
	ApiKey *string `json:"api_key,omitempty"`
}

// NewApiKeyCreatedResponse instantiates a new ApiKeyCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyCreatedResponse() *ApiKeyCreatedResponse {
	this := ApiKeyCreatedResponse{}
	return &this
}

// NewApiKeyCreatedResponseWithDefaults instantiates a new ApiKeyCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyCreatedResponseWithDefaults() *ApiKeyCreatedResponse {
	this := ApiKeyCreatedResponse{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiKeyCreatedResponse) GetKey() ApiKeyResponse {
	if o == nil || IsNil(o.Key) {
		var ret ApiKeyResponse
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyCreatedResponse) GetKeyOk() (*ApiKeyResponse, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiKeyCreatedResponse) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given ApiKeyResponse and assigns it to the Key field.
func (o *ApiKeyCreatedResponse) SetKey(v ApiKeyResponse) {
	o.Key = &v
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *ApiKeyCreatedResponse) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKeyCreatedResponse) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *ApiKeyCreatedResponse) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *ApiKeyCreatedResponse) SetApiKey(v string) {
	o.ApiKey = &v
}

func (o ApiKeyCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.ApiKey) {
		toSerialize["api_key"] = o.ApiKey
	}
	return toSerialize, nil
}

type NullableApiKeyCreatedResponse struct {
	value *ApiKeyCreatedResponse
	isSet bool
}

func (v NullableApiKeyCreatedResponse) Get() *ApiKeyCreatedResponse {
	return v.value
}

func (v *NullableApiKeyCreatedResponse) Set(val *ApiKeyCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyCreatedResponse(val *ApiKeyCreatedResponse) *NullableApiKeyCreatedResponse {
	return &NullableApiKeyCreatedResponse{value: val, isSet: true}
}

func (v NullableApiKeyCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


