/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PolicyListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyListResponse{}

// PolicyListResponse struct for PolicyListResponse
type PolicyListResponse struct {
	Policies []PolicyResponse `json:"policies,omitempty"`
}

// NewPolicyListResponse instantiates a new PolicyListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyListResponse() *PolicyListResponse {
	this := PolicyListResponse{}
	return &this
}

// NewPolicyListResponseWithDefaults instantiates a new PolicyListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyListResponseWithDefaults() *PolicyListResponse {
	this := PolicyListResponse{}
	return &this
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *PolicyListResponse) GetPolicies() []PolicyResponse {
	if o == nil || IsNil(o.Policies) {
		var ret []PolicyResponse
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyListResponse) GetPoliciesOk() ([]PolicyResponse, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *PolicyListResponse) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []PolicyResponse and assigns it to the Policies field.
func (o *PolicyListResponse) SetPolicies(v []PolicyResponse) {
	o.Policies = v
}

func (o PolicyListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	return toSerialize, nil
}

type NullablePolicyListResponse struct {
	value *PolicyListResponse
	isSet bool
}

func (v NullablePolicyListResponse) Get() *PolicyListResponse {
	return v.value
}

func (v *NullablePolicyListResponse) Set(val *PolicyListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyListResponse(val *PolicyListResponse) *NullablePolicyListResponse {
	return &NullablePolicyListResponse{value: val, isSet: true}
}

func (v NullablePolicyListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


