/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreatePolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePolicyRequest{}

// CreatePolicyRequest struct for CreatePolicyRequest
type CreatePolicyRequest struct {
	SecretPathPattern string `json:"secret_path_pattern"`
	PrincipalType string `json:"principal_type"`
	PrincipalId string `json:"principal_id"`
	Permissions []string `json:"permissions"`
	Conditions map[string]interface{} `json:"conditions,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

type _CreatePolicyRequest CreatePolicyRequest

// NewCreatePolicyRequest instantiates a new CreatePolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePolicyRequest(secretPathPattern string, principalType string, principalId string, permissions []string) *CreatePolicyRequest {
	this := CreatePolicyRequest{}
	this.SecretPathPattern = secretPathPattern
	this.PrincipalType = principalType
	this.PrincipalId = principalId
	this.Permissions = permissions
	return &this
}

// NewCreatePolicyRequestWithDefaults instantiates a new CreatePolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePolicyRequestWithDefaults() *CreatePolicyRequest {
	this := CreatePolicyRequest{}
	return &this
}

// GetSecretPathPattern returns the SecretPathPattern field value
func (o *CreatePolicyRequest) GetSecretPathPattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretPathPattern
}

// GetSecretPathPatternOk returns a tuple with the SecretPathPattern field value
// and a boolean to check if the value has been set.
func (o *CreatePolicyRequest) GetSecretPathPatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretPathPattern, true
}

// SetSecretPathPattern sets field value
func (o *CreatePolicyRequest) SetSecretPathPattern(v string) {
	o.SecretPathPattern = v
}

// GetPrincipalType returns the PrincipalType field value
func (o *CreatePolicyRequest) GetPrincipalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value
// and a boolean to check if the value has been set.
func (o *CreatePolicyRequest) GetPrincipalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalType, true
}

// SetPrincipalType sets field value
func (o *CreatePolicyRequest) SetPrincipalType(v string) {
	o.PrincipalType = v
}

// GetPrincipalId returns the PrincipalId field value
func (o *CreatePolicyRequest) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *CreatePolicyRequest) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *CreatePolicyRequest) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetPermissions returns the Permissions field value
func (o *CreatePolicyRequest) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *CreatePolicyRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Permissions, true
}

// SetPermissions sets field value
func (o *CreatePolicyRequest) SetPermissions(v []string) {
	o.Permissions = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *CreatePolicyRequest) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePolicyRequest) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *CreatePolicyRequest) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *CreatePolicyRequest) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *CreatePolicyRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePolicyRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CreatePolicyRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *CreatePolicyRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o CreatePolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secret_path_pattern"] = o.SecretPathPattern
	toSerialize["principal_type"] = o.PrincipalType
	toSerialize["principal_id"] = o.PrincipalId
	toSerialize["permissions"] = o.Permissions
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

func (o *CreatePolicyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secret_path_pattern",
		"principal_type",
		"principal_id",
		"permissions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePolicyRequest := _CreatePolicyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePolicyRequest)

	if err != nil {
		return err
	}

	*o = CreatePolicyRequest(varCreatePolicyRequest)

	return err
}

type NullableCreatePolicyRequest struct {
	value *CreatePolicyRequest
	isSet bool
}

func (v NullableCreatePolicyRequest) Get() *CreatePolicyRequest {
	return v.value
}

func (v *NullableCreatePolicyRequest) Set(val *CreatePolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePolicyRequest(val *CreatePolicyRequest) *NullableCreatePolicyRequest {
	return &NullableCreatePolicyRequest{value: val, isSet: true}
}

func (v NullableCreatePolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


