/*
1Claw API

Secure secret management for AI agents. Provides vaults, secrets, policy-based access control, agent identity, Intents API, sharing, billing, and audit logging.  All endpoints require JWT Bearer authentication unless marked with `security: []`. 

API version: 2.6.0
Contact: ops@1claw.xyz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupRequest{}

// SignupRequest struct for SignupRequest
type SignupRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	DisplayName *string `json:"display_name,omitempty"`
}

type _SignupRequest SignupRequest

// NewSignupRequest instantiates a new SignupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupRequest(email string, password string) *SignupRequest {
	this := SignupRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewSignupRequestWithDefaults instantiates a new SignupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupRequestWithDefaults() *SignupRequest {
	this := SignupRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *SignupRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SignupRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *SignupRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SignupRequest) SetPassword(v string) {
	o.Password = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *SignupRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *SignupRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *SignupRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

func (o SignupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	return toSerialize, nil
}

func (o *SignupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignupRequest := _SignupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignupRequest)

	if err != nil {
		return err
	}

	*o = SignupRequest(varSignupRequest)

	return err
}

type NullableSignupRequest struct {
	value *SignupRequest
	isSet bool
}

func (v NullableSignupRequest) Get() *SignupRequest {
	return v.value
}

func (v *NullableSignupRequest) Set(val *SignupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupRequest(val *SignupRequest) *NullableSignupRequest {
	return &NullableSignupRequest{value: val, isSet: true}
}

func (v NullableSignupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


